import Proofs.InferenceCall.Registry
import Proofs.Conformance.ContractTypes

namespace Conformance.InferenceRegistry
open InferenceCall.Registry
open Conformance.Contracts

/-- Metadata labels are intentionally projected out of resource identity. -/
structure Desired where
  config : Config
  name : String
  catalog : String
  deriving DecidableEq, Repr

inductive Action where
  | reconcile (desired : Option Desired)
  | acquire
  /-- Release one real permit taken from the named pool. -/
  | release (pool : Nat)
  deriving DecidableEq, Repr

structure Observation where
  admittingGeneration : Option Nat
  capacity : Nat
  held : Nat
  pool : Nat
  deriving DecidableEq, Repr

def observe (s : State) : Observation :=
  ⟨s.admitting.map (·.generation), InferenceCall.Registry.capacity s, s.held, s.pool⟩

def step (s : State) : Action → State
  | .reconcile d => InferenceCall.Registry.reconcile s (d.map (·.config))
  | .acquire => (InferenceCall.Registry.acquire s).getD s
  | .release pool => InferenceCall.Registry.release s pool

def replay (s : State) : List Action → List Observation
  | [] => []
  | action :: rest => let post := step s action; observe post :: replay post rest

structure Case where
  name : String
  actions : List Action
  expected : List Observation
  deriving DecidableEq, Repr

def initial : State := ⟨none, none, 0, 0⟩

/-- Every expected observation is independently stated, not generated by replay.
Queue intent and assigned-waiter accounting remain covered by ControllerBookkeeping. -/
def cases : List Case := [
  ⟨"metadata_name_catalog_stutter",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 2, true⟩, "renamed", "model-b"⟩),
     .acquire,
     .acquire,
     .release 1],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 1, 2, 2, 1⟩,
     ⟨some 1, 2, 2, 1⟩,
     ⟨some 1, 2, 1, 1⟩]⟩,
  ⟨"capacity_increase_admits_during_drain",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 3, true⟩, "backend", "model-a"⟩),
     .acquire,
     .release 1,
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 2, 3, 1, 1⟩,
     ⟨some 2, 3, 2, 1⟩,
     ⟨some 2, 3, 1, 1⟩,
     ⟨some 2, 3, 2, 1⟩]⟩,
  ⟨"capacity_decrease_waits_for_excess",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .acquire,
     .reconcile (some ⟨⟨7, 2, 1, true⟩, "backend", "model-a"⟩),
     .acquire,
     .release 1,
     .acquire,
     .release 1,
     .acquire,
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 1, 2, 2, 1⟩,
     ⟨some 2, 1, 2, 1⟩,
     ⟨some 2, 1, 2, 1⟩,
     ⟨some 2, 1, 1, 1⟩,
     ⟨some 2, 1, 1, 1⟩,
     ⟨some 2, 1, 0, 1⟩,
     ⟨some 2, 1, 1, 1⟩,
     ⟨some 2, 1, 1, 1⟩]⟩,
  ⟨"removed_while_in_flight",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 3, true⟩, "backend", "model-a"⟩),
     .reconcile none,
     .release 1,
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 2, 3, 1, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨none, 0, 0, 1⟩]⟩,
  ⟨"unavailable_then_healthy_before_release",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 2, false⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 3, 2, true⟩, "backend", "model-a"⟩),
     .release 1,
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨some 3, 2, 0, 2⟩,
     ⟨some 3, 2, 0, 2⟩,
     ⟨some 3, 2, 1, 2⟩]⟩,
  ⟨"unavailable_through_release_then_healthy",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 2, false⟩, "backend", "model-a"⟩),
     .release 1,
     .acquire,
     .reconcile (some ⟨⟨7, 3, 2, true⟩, "backend", "model-a"⟩),
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨none, 0, 0, 1⟩,
     ⟨some 3, 2, 0, 2⟩,
     ⟨some 3, 2, 1, 2⟩]⟩,
  ⟨"latest_configuration_wins",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 3, true⟩, "backend", "model-a"⟩),
     .reconcile (some ⟨⟨7, 3, 4, true⟩, "backend", "model-a"⟩),
     .reconcile (some ⟨⟨7, 4, 1, true⟩, "backend", "model-a"⟩),
     .acquire,
     .release 1,
     .acquire,
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 2, 3, 1, 1⟩,
     ⟨some 3, 4, 1, 1⟩,
     ⟨some 4, 1, 1, 1⟩,
     ⟨some 4, 1, 1, 1⟩,
     ⟨some 4, 1, 0, 1⟩,
     ⟨some 4, 1, 1, 1⟩,
     ⟨some 4, 1, 1, 1⟩]⟩,
  ⟨"resource_change_with_unchanged_capacity_replaces",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨8, 2, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .release 1,
     .acquire],
    [⟨some 1, 2, 0, 1⟩,
     ⟨some 1, 2, 1, 1⟩,
     ⟨some 2, 2, 1, 1⟩,
     ⟨some 2, 2, 2, 1⟩,
     ⟨some 2, 2, 1, 1⟩,
     ⟨some 2, 2, 2, 1⟩]⟩
  ]

theorem all_cases_replay : cases.all (fun c => replay initial c.actions == c.expected) = true := by
  native_decide

def natOptionJson : Option Nat → String
  | none => "null"
  | some n => toString n

def configJson (d : Desired) : String :=
  "{\"key\":" ++ toString d.config.key ++ ",\"generation\":" ++ toString d.config.generation
  ++ ",\"capacity\":" ++ toString d.config.capacity ++ ",\"available\":" ++ toString d.config.available
  ++ ",\"name\":" ++ jsonString d.name ++ ",\"catalog\":" ++ jsonString d.catalog ++ "}"

def actionJson : Action → String
  | .reconcile d => "{\"kind\":\"reconcile\",\"desired\":" ++ (d.map configJson).getD "null" ++ "}"
  | .acquire => "{\"kind\":\"acquire\"}"
  | .release pool => "{\"kind\":\"release\",\"pool\":" ++ toString pool ++ "}"

def observationJson (o : Observation) : String :=
  "{\"admitting_generation\":" ++ natOptionJson o.admittingGeneration
  ++ ",\"capacity\":" ++ toString o.capacity ++ ",\"held\":" ++ toString o.held
  ++ ",\"pool\":" ++ toString o.pool ++ "}"

def casesJson : String := jsonArray (cases.map fun c =>
  "{\"name\":" ++ jsonString c.name ++ ",\"actions\":" ++ jsonArray (c.actions.map actionJson)
  ++ ",\"expected\":" ++ jsonArray (c.expected.map observationJson) ++ "}")

end Conformance.InferenceRegistry
