import Proofs.InferenceCall.Registry
import Proofs.Conformance.ContractTypes

namespace Conformance.InferenceRegistry
open InferenceCall.Registry
open Conformance.Contracts

/-- Metadata labels are intentionally projected out of resource identity. -/
structure Desired where
  config : Config
  name : String
  catalog : String
  deriving DecidableEq, Repr

inductive Action where
  | reconcile (desired : Option Desired)
  | acquire
  | release (generation : Nat) (returnedPermit : Bool)
  deriving DecidableEq, Repr

structure Observation where
  pendingGeneration : Option Nat
  controllerGeneration : Option Nat
  capacity : Nat
  inFlight : Nat
  permits : Nat
  isOpen : Bool
  deriving DecidableEq, Repr

def observe (s : State) : Observation :=
  ⟨(if !s.isOpen && s.controller.isSome then (availableDesired s.desired).map (·.generation) else none), s.controller.map (·.config.generation),
    (s.controller.map (·.config.capacity)).getD 0,
    (s.controller.map (·.inFlight)).getD 0,
    (s.controller.map (·.permits)).getD 0, s.isOpen⟩

def step (s : State) : Action → State
  | .reconcile d => InferenceCall.Registry.reconcile s (d.map (·.config))
  | .acquire => (InferenceCall.Registry.acquire s).getD s
  | .release generation returned => InferenceCall.Registry.release s generation returned

def replay (s : State) : List Action → List Observation
  | [] => []
  | action :: rest => let post := step s action; observe post :: replay post rest

structure Case where
  name : String
  actions : List Action
  expected : List Observation
  deriving DecidableEq, Repr

def initial : State := ⟨none, none, false⟩

/-- Every expected observation is independently stated, not generated by replay.
Queue intent and assigned-waiter accounting remain covered by ControllerBookkeeping. -/
def cases : List Case := [
  ⟨"metadata_name_catalog_stutter",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 2, true⟩, "renamed", "model-b"⟩),
     .acquire,
     .acquire,
     .release 1 true],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨none, some 1, 2, 2, 2, true⟩,
     ⟨none, some 1, 2, 2, 2, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩]⟩,
  ⟨"capacity_increase_serial_drain",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 3, true⟩, "backend", "model-a"⟩),
     .acquire,
     .release 1 true,
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨none, some 2, 3, 0, 0, true⟩,
     ⟨none, some 2, 3, 1, 1, true⟩]⟩,
  ⟨"capacity_decrease_serial_drain",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .acquire,
     .reconcile (some ⟨⟨7, 2, 1, true⟩, "backend", "model-a"⟩),
     .release 1 true,
     .acquire,
     .release 1 true,
     .acquire,
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨none, some 1, 2, 2, 2, true⟩,
     ⟨some 2, some 1, 2, 2, 2, false⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨none, some 2, 1, 0, 0, true⟩,
     ⟨none, some 2, 1, 1, 1, true⟩,
     ⟨none, some 2, 1, 1, 1, true⟩]⟩,
  ⟨"removed_while_replacement_pending",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 3, true⟩, "backend", "model-a"⟩),
     .reconcile none,
     .release 1 true,
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨none, some 1, 2, 1, 1, false⟩,
     ⟨none, none, 0, 0, 0, false⟩,
     ⟨none, none, 0, 0, 0, false⟩]⟩,
  ⟨"unavailable_then_healthy_before_drain",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 2, false⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 3, 2, true⟩, "backend", "model-a"⟩),
     .release 1 true,
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨none, some 1, 2, 1, 1, false⟩,
     ⟨none, some 1, 2, 1, 1, false⟩,
     ⟨some 3, some 1, 2, 1, 1, false⟩,
     ⟨none, some 3, 2, 0, 0, true⟩,
     ⟨none, some 3, 2, 1, 1, true⟩]⟩,
  ⟨"unavailable_through_drain_then_healthy",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 2, false⟩, "backend", "model-a"⟩),
     .release 1 true,
     .acquire,
     .reconcile (some ⟨⟨7, 3, 2, true⟩, "backend", "model-a"⟩),
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨none, some 1, 2, 1, 1, false⟩,
     ⟨none, none, 0, 0, 0, false⟩,
     ⟨none, none, 0, 0, 0, false⟩,
     ⟨none, some 3, 2, 0, 0, true⟩,
     ⟨none, some 3, 2, 1, 1, true⟩]⟩,
  ⟨"latest_pending_configuration_wins",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨7, 2, 3, true⟩, "backend", "model-a"⟩),
     .reconcile (some ⟨⟨7, 3, 4, true⟩, "backend", "model-a"⟩),
     .reconcile (some ⟨⟨7, 4, 1, true⟩, "backend", "model-a"⟩),
     .release 1 true,
     .acquire,
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨some 3, some 1, 2, 1, 1, false⟩,
     ⟨some 4, some 1, 2, 1, 1, false⟩,
     ⟨none, some 4, 1, 0, 0, true⟩,
     ⟨none, some 4, 1, 1, 1, true⟩,
     ⟨none, some 4, 1, 1, 1, true⟩]⟩,
  ⟨"resource_change_with_unchanged_capacity_replaces",
    [.reconcile (some ⟨⟨7, 1, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .reconcile (some ⟨⟨8, 2, 2, true⟩, "backend", "model-a"⟩),
     .acquire,
     .release 1 true,
     .acquire],
    [⟨none, some 1, 2, 0, 0, true⟩,
     ⟨none, some 1, 2, 1, 1, true⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨some 2, some 1, 2, 1, 1, false⟩,
     ⟨none, some 2, 2, 0, 0, true⟩,
     ⟨none, some 2, 2, 1, 1, true⟩]⟩
  ]

theorem all_cases_replay : cases.all (fun c => replay initial c.actions == c.expected) = true := by
  native_decide

def natOptionJson : Option Nat → String
  | none => "null"
  | some n => toString n

def configJson (d : Desired) : String :=
  "{\"key\":" ++ toString d.config.key ++ ",\"generation\":" ++ toString d.config.generation
  ++ ",\"capacity\":" ++ toString d.config.capacity ++ ",\"available\":" ++ toString d.config.available
  ++ ",\"name\":" ++ jsonString d.name ++ ",\"catalog\":" ++ jsonString d.catalog ++ "}"

def actionJson : Action → String
  | .reconcile d => "{\"kind\":\"reconcile\",\"desired\":" ++ (d.map configJson).getD "null" ++ "}"
  | .acquire => "{\"kind\":\"acquire\"}"
  | .release gen returned => "{\"kind\":\"release\",\"generation\":" ++ toString gen
      ++ ",\"returned_permit\":" ++ toString returned ++ "}"

def observationJson (o : Observation) : String :=
  "{\"pending_generation\":" ++ natOptionJson o.pendingGeneration
  ++ ",\"controller_generation\":" ++ natOptionJson o.controllerGeneration
  ++ ",\"capacity\":" ++ toString o.capacity ++ ",\"in_flight\":" ++ toString o.inFlight
  ++ ",\"permits\":" ++ toString o.permits ++ ",\"is_open\":" ++ toString o.isOpen ++ "}"

def casesJson : String := jsonArray (cases.map fun c =>
  "{\"name\":" ++ jsonString c.name ++ ",\"actions\":" ++ jsonArray (c.actions.map actionJson)
  ++ ",\"expected\":" ++ jsonArray (c.expected.map observationJson) ++ "}")

end Conformance.InferenceRegistry
