type CodeReviewEvidencePage11 {
  evidence_id: String @index(unique: true) @immutable
  evidence_chunk_176: String @immutable
  evidence_chunk_177: String @immutable
  evidence_chunk_178: String @immutable
  evidence_chunk_179: String @immutable
  evidence_chunk_180: String @immutable
  evidence_chunk_181: String @immutable
  evidence_chunk_182: String @immutable
  evidence_chunk_183: String @immutable
  evidence_chunk_184: String @immutable
  evidence_chunk_185: String @immutable
  evidence_chunk_186: String @immutable
  evidence_chunk_187: String @immutable
  evidence_chunk_188: String @immutable
  evidence_chunk_189: String @immutable
  evidence_chunk_190: String @immutable
  evidence_chunk_191: String @immutable
}
