type CodeReviewEvidencePage16 {
  evidence_id: String @index(unique: true) @immutable
  evidence_chunk_256: String @immutable
  evidence_chunk_257: String @immutable
  evidence_chunk_258: String @immutable
  evidence_chunk_259: String @immutable
  evidence_chunk_260: String @immutable
  evidence_chunk_261: String @immutable
  evidence_chunk_262: String @immutable
  evidence_chunk_263: String @immutable
  evidence_chunk_264: String @immutable
  evidence_chunk_265: String @immutable
  evidence_chunk_266: String @immutable
  evidence_chunk_267: String @immutable
  evidence_chunk_268: String @immutable
  evidence_chunk_269: String @immutable
  evidence_chunk_270: String @immutable
  evidence_chunk_271: String @immutable
}
