type CodeReviewEvidencePage5 {
  evidence_id: String @index(unique: true) @immutable
  evidence_chunk_80: String @immutable
  evidence_chunk_81: String @immutable
  evidence_chunk_82: String @immutable
  evidence_chunk_83: String @immutable
  evidence_chunk_84: String @immutable
  evidence_chunk_85: String @immutable
  evidence_chunk_86: String @immutable
  evidence_chunk_87: String @immutable
  evidence_chunk_88: String @immutable
  evidence_chunk_89: String @immutable
  evidence_chunk_90: String @immutable
  evidence_chunk_91: String @immutable
  evidence_chunk_92: String @immutable
  evidence_chunk_93: String @immutable
  evidence_chunk_94: String @immutable
  evidence_chunk_95: String @immutable
}
