type CodeReviewEvidencePage8 {
  evidence_id: String @index(unique: true) @immutable
  evidence_chunk_128: String @immutable
  evidence_chunk_129: String @immutable
  evidence_chunk_130: String @immutable
  evidence_chunk_131: String @immutable
  evidence_chunk_132: String @immutable
  evidence_chunk_133: String @immutable
  evidence_chunk_134: String @immutable
  evidence_chunk_135: String @immutable
  evidence_chunk_136: String @immutable
  evidence_chunk_137: String @immutable
  evidence_chunk_138: String @immutable
  evidence_chunk_139: String @immutable
  evidence_chunk_140: String @immutable
  evidence_chunk_141: String @immutable
  evidence_chunk_142: String @immutable
  evidence_chunk_143: String @immutable
}
