type CodeReviewEvidencePage2 {
  evidence_id: String @index(unique: true) @immutable
  evidence_chunk_32: String @immutable
  evidence_chunk_33: String @immutable
  evidence_chunk_34: String @immutable
  evidence_chunk_35: String @immutable
  evidence_chunk_36: String @immutable
  evidence_chunk_37: String @immutable
  evidence_chunk_38: String @immutable
  evidence_chunk_39: String @immutable
  evidence_chunk_40: String @immutable
  evidence_chunk_41: String @immutable
  evidence_chunk_42: String @immutable
  evidence_chunk_43: String @immutable
  evidence_chunk_44: String @immutable
  evidence_chunk_45: String @immutable
  evidence_chunk_46: String @immutable
  evidence_chunk_47: String @immutable
}
