type CodeReviewEvidencePage1 {
  evidence_id: String @index(unique: true) @immutable
  evidence_chunk_16: String @immutable
  evidence_chunk_17: String @immutable
  evidence_chunk_18: String @immutable
  evidence_chunk_19: String @immutable
  evidence_chunk_20: String @immutable
  evidence_chunk_21: String @immutable
  evidence_chunk_22: String @immutable
  evidence_chunk_23: String @immutable
  evidence_chunk_24: String @immutable
  evidence_chunk_25: String @immutable
  evidence_chunk_26: String @immutable
  evidence_chunk_27: String @immutable
  evidence_chunk_28: String @immutable
  evidence_chunk_29: String @immutable
  evidence_chunk_30: String @immutable
  evidence_chunk_31: String @immutable
}
