self-hosted-runner:
  labels:
    - macOS
    - ARM64
    - studio
    - studio-1
    - studio-2
    - ci-runtime
    - ci-support
    - ci-desktop
    - ci-cli
    - Linux
    - X64
    - spark
    - workstation-1
