import Proofs.Basic
import Proofs.Transcript.State
import Proofs.StreamingResponse.State

/-!
# Compaction State

`PromptView` -- the in-memory prompt-input projection that a
`TranscriptReducer` transforms. Unlike `Transcript.TranscriptState`,
a `PromptView` is *not* the durable transcript; reducing a `PromptView`
does not mutate any durable `AgentMessage` or `AgentToolCall` row.

This file defines the operand type and three predicates:
`PairsClosedInMessages` (list-level pair atomicity), `ViewCoherent`
(local conjunction: pairs + ordered + unique sequences), and
`safeToReduce` (every retained tool-result message belongs to a
terminal streaming response -- cites #190's `Status.isTerminal`).
-/

namespace Compaction

open Transcript (Sequence MessageId MessageRow MessageKind ToolResultKey
                 MessageRole StrictlyIncreasingMessages UniqueMessageSequences)

/-- Opaque handle to a compaction-produced summary blob. The summary
text is generated by an LLM and is not formally constrained; the model
treats it as an identifier. The prompt builder later prepends the
summary as a synthetic user message. -/
structure SummaryHandle where
  payload : Nat
  deriving DecidableEq, Repr

/-- The slice of TranscriptState that a TranscriptReducer transforms.
A PromptView is the in-memory prompt input for the next inference call,
not the durable transcript. -/
structure PromptView where
  sessionId        : SessionId
  messages         : List MessageRow
  summary          : Option SummaryHandle
  responseStatuses : MessageId → Option StreamingResponse.Status

namespace PromptView

/-- A messages-only specialization of Transcript's pair-closure
invariant. Every tool-result row in the list has a matching
assistantToolCalls row in the same list whose callIds set contains
the result's callId. -/
def PairsClosedInMessages (msgs : List MessageRow) : Prop :=
  ∀ row, row ∈ msgs →
    ∀ callId key, row.kind = .toolResult callId key →
      ∃ caller, caller ∈ msgs ∧
        caller.role = .assistant ∧
        (∃ callIds, caller.kind = .assistantToolCalls callIds ∧ callId ∈ callIds)

/-- Local coherence for a PromptView: pair atomicity + ordered +
unique sequences. The TranscriptState-level `Coherent` additionally
requires toolCall-side predicates that don't make sense for a
PromptView (a PromptView has no `toolCalls` list). -/
structure ViewCoherent (v : PromptView) : Prop where
  pairs           : PairsClosedInMessages v.messages
  ordered         : StrictlyIncreasingMessages v.messages
  uniqueSequences : UniqueMessageSequences v.messages

/-- A view is safe to reduce only if every retained tool-result message
belongs to a streaming response that has reached a terminal status. -/
def safeToReduce (v : PromptView) : Prop :=
  ∀ row, row ∈ v.messages →
    (∃ callId key, row.kind = .toolResult callId key) →
      ∃ status, v.responseStatuses row.messageId = some status ∧
        isTerminal status

end PromptView

end Compaction
