// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BearerPairingView } from "./BearerPairingView.js";
import type { DesktopBootstrapSummary } from "./DesktopBootstrapSummary.js";
import type { DesktopRuntimeSnapshot } from "./DesktopRuntimeSnapshot.js";

export type BearerPairingResponse = { pairing: BearerPairingView, bootstrap: DesktopBootstrapSummary, client: DesktopRuntimeSnapshot | null, };
