// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of bridge error codes. Additive codes bump contract MINOR;
 * rename/removal/meaning change bumps MAJOR.
 */
export type BridgeErrorCode = "clientNotRunning" | "clientStartFailed" | "notFound" | "invalidArgument" | "unsupported" | "endpointUnreachable" | "stalePreview" | "cascadeDepthExceeded" | "pathEscapesRoot" | "backend" | "pairing" | "unknown";
