// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatSendResult = { sessionId: string, requestId: string, agentDid: string, behaviorId: string | null, };
