// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatSendRequest = { agentDid: string, behaviorId: string | null, sessionId: string | null, content: string, };
