// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopOperationsSnapshotRequest = { agentDid: string | null,
/**
 * Accepted from the client but not yet consumed: snapshot filtering by
 * root request / terminal inclusion is staged (operator-surfaces spec).
 */
rootRequestId: string | null, includeTerminal: boolean | null, };
