// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopListSubagentTreeRequest = { rootRequestId: string, agentDid: string | null, includeTerminal: boolean | null, maxDepth: number | null, };
