// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopInterruptRequest = { requestId: string, agentDid: string | null,
/**
 * Currently always `"userCancelled"` per spec line 907. Kept as a String
 * so future cause variants don't require an enum migration here.
 */
cause: string, cascade: boolean, expectedPreviewSignature: string | null, };
