// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventTriggerSaveRequest = { triggerId: string, taskId: string, sourceCollection: string, eventKind: string, filter: string | null, enabled: boolean | null, concurrency: string | null, };
