// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoalView = { goalId: string, objective: string | null, status: string | null, tokenBudget: number | null, tokensUsed: number, activeTimeSeconds: number, consecutiveBlockedAudits: number, continuationSequence: number, wrapupRequested: boolean, wrapupCompleted: boolean, lastBlockedReason: string | null, lastFailure: string | null, completionEvidence: string | null, };
