// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CascadeCancelPreview } from "./CascadeCancelPreview.js";

/**
 * Result envelope for `desktop_interrupt_request`. Field semantics are
 * normative per the design spec line 922–942:
 * - `accepted = true` iff the bridge latched (or confirmed already-latched)
 *   `interrupt_requested_at` for `request_id`.
 * - `already_interrupted = true` iff the field was non-null prior to the
 *   call; `accepted` is still `true` in that case.
 * - `stale_preview = true` is mutually exclusive with `accepted = true`.
 *   On signature mismatch the bridge returns `accepted: false`,
 *   `stale_preview: true`, and a fresh `preview` for the UI to redraw.
 * - `interrupt_requested_at` is the canonical timestamp the bridge observed
 *   on the document after the call. Null only on a non-already-interrupted
 *   failure.
 */
export type InterruptRequestResult = { requestId: string, accepted: boolean, interruptRequestedAt: string | null, alreadyInterrupted: boolean, stalePreview: boolean, preview: CascadeCancelPreview | null, };
