// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the MCP health status panel (panel-278).
 *
 * Mirrors the persisted `ToolServiceHealthState` collection — the agent's
 * `health_checker` upserts these every cycle (default 30 s) so the
 * desktop sees the K-model state evolve over time without needing an
 * in-process agent runtime.
 *
 * `status` is the internal `HealthStateInternal` projection
 * (`healthy` / `stale` / `evicted` / `reconnecting`) so the operator UI
 * can distinguish back-off from in-flight retry; the public three-state
 * `HealthStatus` collapses `evicted` and `reconnecting` to `unreachable`.
 */
export type MCPServiceHealthView = { serviceId: string, agentDid: string | null, endpoint: string | null, status: string | null, toolCount: number | null, failureCount: number | null, kMax: number | null, backoffUntil: string | null, lastProbeAt: string | null, lastSeen: string | null, lastErrorClass: string | null, lastErrorMessage: string | null, updatedAt: string | null, };
