// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkSavedPeerView = { peerId: string, label: string, addr: string, agentDid: string, source: string | null, };
