// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkReplicatorView } from "./NetworkReplicatorView.js";
import type { NetworkSavedPeerView } from "./NetworkSavedPeerView.js";

export type NetworkStatusView = { localPeerId: string | null, localPeerIdError: string | null, listenAddresses: Array<string>, listenAddressesError: string | null, connectedPeers: Array<string>, connectedPeersError: string | null, replicators: Array<NetworkReplicatorView>, replicatorsError: string | null, savedPeers: Array<NetworkSavedPeerView>, };
