// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopBootstrapSummary } from "./DesktopBootstrapSummary.js";
import type { DesktopRuntimeSnapshot } from "./DesktopRuntimeSnapshot.js";
import type { PeerMutationView } from "./PeerMutationView.js";

export type PeerRemoveResponse = { mutation: PeerMutationView, bootstrap: DesktopBootstrapSummary, client: DesktopRuntimeSnapshot | null, };
