// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerMutationView = { peerId: string, label: string, addr: string, connected: boolean, warning: string | null, };
