// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PendingTurnView = { requestId: string, content: string, selectedSkillIds: Array<string>, lifecycleState: string | null, createdAt: string | null, };
