// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionSetContract = { name: string,
/**
 * `"read"` or `"mutate"` — never mixed within one set.
 */
kind: string, };
