// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of writing an AgentToolApproval decision for a held call.
 */
export type ResolveHoldResult = { approvalId: string, toolCallId: string, decision: string, };
