// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeView = { processState: string | null, reconcilePhase: string | null, lastReconcileResult: string | null, lastReconcileError: string | null, updatedAt: string | null, behaviorExecutorCapacity: number | null, behaviorExecutorQueueDepth: number | null, runnableBehaviorCount: number | null, unavailableBehaviorCount: number | null, };
