// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduleView = { scheduleId: string, taskId: string | null, intervalSecs: number | null, cron: string | null, timezone: string | null, missedRunPolicy: string | null, enabled: boolean | null, concurrency: string | null, nextRunAt: string | null, lastAttemptAt: string | null, lastStatus: string | null, lastError: string | null, fireCount: number | null, };
