// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StuckWorkDiagnosticView = { requestId: string, sessionId: string | null, severity: string, reason: string, deadlineAgeMs: number | null, lastProgressAgeMs: number | null, toolCallId: string | null, toolName: string | null, stuckSince: string | null, };
