// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubagentEdgeView = { parentRequestId: string, childRequestId: string, parentToolCallId: string | null, toolName: string | null, awaitMode: string | null, cancelPolicy: string | null, lifecycleState: string | null, };
