// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskRecentRunsView = { totalFires: number, lastAttemptAt: string | null, lastStatus: string | null, lastError: string | null, scheduleCount: number, eventTriggerCount: number, };
