// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolServiceToolView } from "./ToolServiceToolView.js";

export type ToolServiceTestResult = { serviceId: string, endpoint: string, status: string, toolCount: number, tools: Array<ToolServiceToolView>, error: string | null, };
