// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolServiceRegistryView = { serviceId: string, displayName: string | null, description: string | null, hostname: string | null, tailscaleIp: string | null, lanIp: string | null, mcpPort: number | null, mcpPath: string | null, status: string | null, version: string | null, updatedAt: string | null, };
