import { vi } from "vitest";

import type {
  AgentConfigSaveRequest,
  BackendSaveRequest,
  BehaviorSaveRequest,
  BootstrapSummary,
  DeploymentView,
  EventSourceSaveRequest,
  InferenceProfileSaveRequest,
  ScheduleSaveRequest,
  TaskRunResult,
  TaskSaveRequest,
  ToolsSaveRequest,
  ToolServiceSaveRequest,
  ToolServiceTestRequest,
  ToolServiceTestResult,
  TriggerSaveRequest,
} from "@source-inc/gents-desktop-client";

export const runResult: TaskRunResult = {
  requestDocId: "bae-run",
  requestId: "run-1",
  sessionId: "session-1",
  agentDid: "did:key:z6MkAgent",
  behaviorId: "default",
  status: "submitted",
  lifecycleState: "queued",
};

export const deployment: DeploymentView = {
  peerId: "peer-1",
  label: "Local Agent",
  agentDid: "did:key:z6MkAgent",
  addr: "iroh://local",
  source: "local",
  graphql: null,
  dialSucceeded: true,
  chatSafe: true,
  routes: [],
  pairing: [],
  lastError: null,
  agentPrincipal: {
    agentDid: "did:key:z6MkAgent",
    displayName: "Local Agent",
    defaultBehaviorId: "default",
    enabled: true,
    createdAt: null,
    createdBy: null,
  },
  principalConfig: null,
  behaviorConfigs: [
    {
      behavior_id: "default",
      agent_did: "did:key:z6MkAgent",
      display_name: "Default",
      description: null,
      context_id: "context-a",
      inference_profile_id: "profile-a",
      enabled: true,
      tags: [],
      created_at: null,
    },
    {
      behavior_id: "ops",
      agent_did: "did:key:z6MkAgent",
      display_name: "Ops",
      description: null,
      context_id: "context-b",
      inference_profile_id: "profile-b",
      enabled: true,
      tags: [],
      created_at: null,
    },
  ],
  runtime: null,
  behaviorReadiness: {
    source: { state: "current" },
    activeGeneration: 1,
    routerGeneration: 1,
    updatedAt: "2026-08-28T00:00:00Z",
    behaviors: [
      { state: "ready", behaviorId: "default" },
      { state: "ready", behaviorId: "ops" },
    ],
  },
  behaviors: [
    {
      behaviorId: "default",
      agentDid: "did:key:z6MkAgent",
      displayName: "Default",
      description: null,
      contextId: "context-a",
      inferenceProfileId: "profile-a",
      enabled: true,
      isDefault: true,
      tags: [],
      createdAt: null,
    },
    {
      behaviorId: "ops",
      agentDid: "did:key:z6MkAgent",
      displayName: "Ops",
      description: null,
      contextId: "context-b",
      inferenceProfileId: "profile-b",
      enabled: true,
      isDefault: false,
      tags: [],
      createdAt: null,
    },
  ],
  behaviorEnvironments: [
    {
      behaviorId: "default",
      displayName: "Default",
      enabled: true,
      isDefault: true,
      modelName: "model-a",
      inferenceProfileName: "Profile A",
      workspaceRoot: "/tmp/work",
      fileAccess: "read-only",
      bashAccess: "read-only",
      networkAccess: null,
      skillNames: [],
      sessionCount: 0,
      activeSessionCount: 0,
    },
    {
      behaviorId: "ops",
      displayName: "Ops",
      enabled: true,
      isDefault: false,
      modelName: "model-b",
      inferenceProfileName: "Profile B",
      workspaceRoot: null,
      fileAccess: "off",
      bashAccess: "off",
      networkAccess: null,
      skillNames: [],
      sessionCount: 0,
      activeSessionCount: 0,
    },
  ],
  inferenceBackends: [
    {
      backendId: "backend-a",
      name: "Backend A",
      providerKind: "OpenAiCompatible",
      openaiWireApi: null,
      endpoint: "http://127.0.0.1:8000/v1",
      authKind: null,
      connectTimeoutSecs: null,
      discoveryTimeoutSecs: null,
      apiKeyConfigured: false,
      apiKeyEnvVar: null,
      maxConcurrent: null,
      maxQueueDepth: null,
      enabled: true,
      models: ["model-a"],
      probeStatus: null,
    },
    {
      backendId: "backend-b",
      name: "Backend B",
      providerKind: "OpenAiCompatible",
      openaiWireApi: null,
      endpoint: "http://127.0.0.1:9000/v1",
      authKind: null,
      connectTimeoutSecs: null,
      discoveryTimeoutSecs: null,
      apiKeyConfigured: false,
      apiKeyEnvVar: null,
      maxConcurrent: null,
      maxQueueDepth: null,
      enabled: true,
      models: ["model-b"],
      probeStatus: null,
    },
  ],
  inferenceProfiles: [
    {
      agent_did: "did:key:z6MkAgent",
      profile_id: "profile-a",
      display_name: "Profile A",
      description: null,
      backend_id: "backend-a",
      model_name: "model-a",
      reasoning_effort: null,
      context_window: 131072,
      max_output_tokens: null,
      sampling_id: null,
      execution_id: null,
      tags: [],
    },
    {
      agent_did: "did:key:z6MkAgent",
      profile_id: "profile-b",
      display_name: "Profile B",
      description: null,
      backend_id: "backend-b",
      model_name: "model-b",
      reasoning_effort: null,
      context_window: 65536,
      max_output_tokens: null,
      sampling_id: null,
      execution_id: null,
      tags: [],
    },
  ],
  inferenceSampling: [],
  inferenceExecution: [],
  contexts: [
    {
      context_id: "context-a",
      agent_did: "did:key:z6MkAgent",
      display_name: "Default context",
      description: null,
      system_prompt: "You are the default behavior.",
      tools_id: "tools-a",
      compaction_id: null,
      skill_ids: null,
      tags: [],
    },
    {
      context_id: "context-b",
      agent_did: "did:key:z6MkAgent",
      display_name: "Ops context",
      description: null,
      system_prompt: "You are the ops behavior.",
      tools_id: "tools-b",
      compaction_id: null,
      skill_ids: null,
      tags: [],
    },
  ],
  compactions: [],
  tools: [
    {
      tools_id: "tools-a",
      agent_did: "did:key:z6MkAgent",
      display_name: "Tools A",
      host: {
        files: { mode: "ReadOnly" },
        bash: { mode: "ReadOnly" },
      },
    },
    {
      tools_id: "tools-b",
      agent_did: "did:key:z6MkAgent",
      display_name: "Tools B",
      host: {
        files: { mode: "ReadOnly" },
        bash: { mode: "ReadOnly" },
      },
    },
  ],
  toolServiceRegistries: [
    {
      service_id: "service-a",
      agent_did: "did:key:z6MkAgent",
      display_name: "Service A",
      description: null,
      hostname: "localhost",
      tailscale_ip: null,
      lan_ip: null,
      mcp_port: 7331,
      mcp_path: "/mcp",
      send_agent_did: null,
      enabled: true,
      tags: [],
    },
  ],
  subagentTargets: [],
  datastoreToolSurfaces: [],
  chainKeyBindings: [],
  skills: [
    {
      skillId: "skill-a",
      agentDid: "did:key:z6MkAgent",
      name: "Skill A",
      description: "Skill A description",
      instructions: "Do skill A things",
      toolRefs: [],
      displayName: "Skill A",
      enabled: true,
      createdAt: null,
    },
  ],
  tasks: [
    {
      taskId: "task-a",
      name: "Task A",
      description: null,
      behaviorId: "default",
      promptTemplate: "Run task A",
      goalObjectiveTemplate: null,
      goalTokenBudget: null,
      hooks: [],
      enabled: true,
      outputSchemaRef: null,
      tags: [],
      recentRuns: {
        totalFires: 0,
        lastAttemptAt: null,
        lastStatus: null,
        lastError: null,
        scheduleCount: 1,
        eventCount: 1,
      },
      runHistory: [],
    },
    {
      taskId: "task-b",
      name: "Task B",
      description: null,
      behaviorId: "ops",
      promptTemplate: "Run task B",
      goalObjectiveTemplate: null,
      goalTokenBudget: null,
      hooks: [],
      enabled: true,
      outputSchemaRef: null,
      tags: [],
      recentRuns: {
        totalFires: 0,
        lastAttemptAt: null,
        lastStatus: null,
        lastError: null,
        scheduleCount: 0,
        eventCount: 0,
      },
      runHistory: [],
    },
  ],
  schedules: [
    {
      agent_did: "did:key:z6MkAgent",
      schedule_id: "timer-a",
      display_name: "Timer A",
      cadence: { kind: "interval", interval_secs: 60 },
      tags: [],
    },
  ],
  eventSources: [
    {
      agent_did: "did:key:z6MkAgent",
      event_source_id: "source-a",
      display_name: "Source A",
      source_collection: "AgentRequest",
      event_kind: "created",
      filter: null,
      correlation_field: null,
      group: null,
      workspace_authority: null,
      tags: [],
    },
  ],
  triggers: [
    {
      config: {
        agent_did: "did:key:z6MkAgent",
        trigger_id: "trigger-a",
        display_name: "Trigger A",
        description: null,
        task_id: "task-a",
        source: { kind: "schedule", schedule_id: "timer-a" },
        enabled: true,
        concurrency: "serial",
        tags: [],
      },
      nextRunAt: null,
      lastAttemptAt: null,
      lastFiredSourceDocId: null,
      lastStatus: null,
      lastError: null,
      fireCount: 0,
    },
  ],
  sessions: [],
  mailboxItems: [],
};

export const bootstrap: BootstrapSummary = {
  defaultAgentHome: "/tmp/agent",
  initAgentName: "Local Agent",
  initAgentDid: "did:key:z6MkAgent",
  initToolCeiling: "Readwrite",
  initToolRoot: "/tmp/work",
  desktopHome: "/tmp/gents",
  peerDirectoryPath: "/tmp/gents/peers.json",
  nodeDataDir: "/tmp/gents/node",
  logFilePath: "/tmp/gents/logs/desktop.log",
  agentHomeExists: true,
  desktopHomeExists: true,
  peerDirectoryExists: true,
  clientStateExists: false,
  savedPeers: [],
};

export function workspaceHandlers() {
  return {
    onBack: vi.fn(),
    onSaveAgentConfig: vi.fn<[(request: AgentConfigSaveRequest) => Promise<unknown>]>(
      () => Promise.resolve(),
    ),
    onSaveBackendConfig: vi.fn<[(request: BackendSaveRequest) => Promise<unknown>]>(
      () => Promise.resolve(),
    ),
    onSaveInferenceProfileConfig: vi.fn<
      [(request: InferenceProfileSaveRequest) => Promise<unknown>]
    >(() => Promise.resolve()),
    onSaveToolsConfig: vi.fn<[(request: ToolsSaveRequest) => Promise<unknown>]>(() =>
      Promise.resolve(),
    ),
    onSaveToolServiceConfig: vi.fn<
      [(request: ToolServiceSaveRequest) => Promise<unknown>]
    >(() => Promise.resolve()),
    onTestToolService: vi.fn<
      [(request: ToolServiceTestRequest) => Promise<ToolServiceTestResult>]
    >(() =>
      Promise.resolve({
        serviceId: "service-a",
        endpoint: "http://localhost:7331/mcp",
        status: "ok",
        toolCount: 0,
        tools: [],
      }),
    ),
    onSaveBehaviorConfig: vi.fn<[(request: BehaviorSaveRequest) => Promise<unknown>]>(
      () => Promise.resolve(),
    ),
    onSaveTaskConfig: vi.fn<[(request: TaskSaveRequest) => Promise<unknown>]>(() =>
      Promise.resolve(),
    ),
    onSaveScheduleConfig: vi.fn<[(request: ScheduleSaveRequest) => Promise<unknown>]>(
      () => Promise.resolve(),
    ),
    onRunSchedule: vi.fn<[(request: { scheduleId: string }) => Promise<TaskRunResult>]>(
      () => Promise.resolve(runResult),
    ),
    onSaveEventSourceConfig: vi.fn<
      [(request: EventSourceSaveRequest) => Promise<unknown>]
    >(() => Promise.resolve()),
    onSaveTriggerConfig: vi.fn<[(request: TriggerSaveRequest) => Promise<unknown>]>(
      () => Promise.resolve(),
    ),
    onRunTask: vi.fn<
      [(request: { taskId: string; args?: unknown }) => Promise<TaskRunResult>]
    >(() => Promise.resolve(runResult)),
  };
}
