//! Conformance fence for the provider-input sanitizer.
//!
//! This fence used to be *social*: a human read `Proofs/PromptAssembly` and
//! hand-wrote assertions against a test-local pairing oracle. Nothing tied the
//! Rust sanitizer to the function the Lean theorems quantify over, so a change
//! to either side could break the correspondence without failing a test. That
//! is not hypothetical — `loop_stream.rs::repair_provider_input` records a bug
//! of exactly this shape, where "the fence described a transform that did not
//! exist".
//!
//! It is now mechanical. Every sanitize expectation below is generated by
//! running the Lean model (`PromptAssembly.Provider.sanitizeForProviderGlobal`)
//! and consumed here verbatim; see
//! `Proofs/Conformance/ContractCases/PromptAssembly.lean`.
//!
//! **Which sanitizer is fenced.** The emitted expectations are the
//! global-resolution proof model. Production implements the per-turn
//! algorithm (`history.rs::resolved_keys_per_turn` mirrors
//! `PromptAssembly.sanitizeTurn`); the two coincide exactly on the emitted
//! witnesses because every witness satisfies `UniqueCallIds` (checked in Lean
//! by `witnessesHaveUniqueCallIds`, aligned by `sanitizeTurn_eq_sanitizeGlobal`).
//! That witness alignment is all this fence claims: content-bearing per-turn
//! soundness and repeated-occurrence transfer remain explicit follow-up (see
//! proofs/README.md), so nothing here asserts a per-turn content guarantee —
//! the global model is a conditional proof oracle, not a second production
//! algorithm.
//!
//! **There is deliberately no provider-validity oracle in this file.** Validity
//! of each expected output is the Lean theorem
//! `Provider.sanitizeForProviderGlobal_sound`. Production that reproduces the
//! emitted output exactly inherits it. Re-deriving pairing rules in Rust would
//! just reintroduce the social fence this replaces.

use gents::compaction::sanitize_history_for_provider;
use gents::llm::message::{
    AssistantContent, Image, Message, Reasoning, Text, ToolCall, ToolFunction, ToolResult,
    ToolResultContent, UserContent,
};
use gents_loop::provider_input::ProviderInputProfile;

use std::collections::HashSet;

use gents::claude_messages::{
    build_messages_body_native, parse_messages_sse, parse_messages_sse_typed, CLAUDE_CODE_IDENTITY,
};
use gents::claude_subscription::ClaudeStreamResponse;
use rig::completion::CompletionError;
use rig::streaming::RawStreamingChoice;

use crate::lean_vocab_test::{
    lean_prompt_assembly_claude_body_cases, lean_prompt_assembly_claude_map_cases,
    lean_prompt_assembly_claude_replay_cases, lean_prompt_assembly_claude_stream_cases,
    lean_prompt_assembly_claude_thinking_stream_cases, lean_prompt_assembly_sanitize_cases,
    LeanClaudeReasoningPart, LeanClaudeStreamBlock, LeanClaudeStreamEvent, LeanPromptAssemblyItem,
    LeanPromptAssemblyRow,
};

/// Stable identities for the abstract ids the model uses. The model abstracts
/// a tool call to a single `ToolCallId`; production pairs on
/// `call_id.unwrap_or(id)` (`history.rs::tool_call_key`). Both fields carry the
/// same string here so the projection is unambiguous; the case where they
/// differ is fenced separately by `pairing_identity_uses_call_id_over_item_id`.
fn call_key(id: u64) -> String {
    format!("call-{id}")
}

fn text_body(index: u64) -> String {
    format!("text-{index}")
}

fn reasoning_body(index: u64) -> String {
    format!("reasoning-{index}")
}

fn tool_call(id: u64) -> ToolCall {
    ToolCall {
        id: call_key(id),
        call_id: Some(call_key(id)),
        function: ToolFunction {
            name: "echo".to_string(),
            arguments: serde_json::json!({}),
        },
        signature: None,
        additional_params: None,
    }
}

/// Build the production `Message` a generated row denotes.
///
/// Total by construction: an unknown role, kind, or item name panics rather
/// than silently producing something the model did not describe.
fn message_of_row(row: &LeanPromptAssemblyRow) -> Message {
    match (row.role.as_str(), row.kind.as_str()) {
        ("assistant", _) => Message::Assistant {
            id: None,
            content: row.content.iter().map(assistant_item).collect(),
        },
        ("user", "toolResult") => {
            let [id] = row.call_ids.as_slice() else {
                panic!("a toolResult row must carry exactly one call id: {row:?}");
            };
            Message::User {
                content: vec![UserContent::ToolResult(ToolResult {
                    id: call_key(*id),
                    call_id: Some(call_key(*id)),
                    content: vec![ToolResultContent::Text(Text {
                        text: format!("{}-result", call_key(*id)),
                    })],
                })],
            }
        }
        ("user", _) => Message::User {
            content: row.content.iter().map(user_item).collect(),
        },
        (role, kind) => panic!("generated row has an unmodeled role/kind: {role}/{kind}"),
    }
}

fn assistant_item(item: &LeanPromptAssemblyItem) -> AssistantContent {
    match item.item.as_str() {
        "text" => AssistantContent::Text(Text {
            text: text_body(item.value),
        }),
        "other" => AssistantContent::Reasoning(Reasoning::new(&reasoning_body(item.value))),
        "call" => AssistantContent::ToolCall(tool_call(item.value)),
        other => panic!("generated content item has an unmodeled tag: {other}"),
    }
}

fn user_item(item: &LeanPromptAssemblyItem) -> UserContent {
    match item.item.as_str() {
        "text" => UserContent::Text(Text {
            text: text_body(item.value),
        }),
        other => panic!("generated user content item has an unmodeled tag: {other}"),
    }
}

/// Project a production `Message` back onto the model's row shape, so output
/// can be compared against the generated expectation on the model's own terms.
fn row_of_message(message: &Message) -> LeanPromptAssemblyRow {
    match message {
        Message::Assistant { content, .. } => {
            let items = content.iter().map(assistant_item_of).collect::<Vec<_>>();
            let call_ids = items
                .iter()
                .filter(|item| item.item == "call")
                .map(|item| item.value)
                .collect::<Vec<_>>();
            LeanPromptAssemblyRow {
                role: "assistant".to_string(),
                kind: if call_ids.is_empty() {
                    "ordinary".to_string()
                } else {
                    "assistantToolCalls".to_string()
                },
                call_ids,
                content: items,
            }
        }
        Message::User { content } => {
            let tool_results = content
                .iter()
                .filter_map(|item| match item {
                    UserContent::ToolResult(tool_result) => Some(tool_result),
                    _ => None,
                })
                .collect::<Vec<_>>();
            if tool_results.is_empty() {
                LeanPromptAssemblyRow {
                    role: "user".to_string(),
                    kind: "ordinary".to_string(),
                    call_ids: Vec::new(),
                    content: content.iter().map(user_item_of).collect(),
                }
            } else {
                assert_eq!(
                    tool_results.len(),
                    1,
                    "production threads exactly one tool result per user message \
                     (loop_stream.rs); the model's row projection assumes it"
                );
                LeanPromptAssemblyRow {
                    role: "user".to_string(),
                    kind: "toolResult".to_string(),
                    call_ids: vec![parse_call_key(&result_key(tool_results[0]))],
                    content: Vec::new(),
                }
            }
        }
        Message::System { .. } => {
            panic!("the PromptAssembly model has no system-row projection")
        }
    }
}

fn assistant_item_of(content: &AssistantContent) -> LeanPromptAssemblyItem {
    match content {
        AssistantContent::Text(text) => LeanPromptAssemblyItem {
            item: "text".to_string(),
            value: parse_suffix(&text.text, "text-"),
        },
        AssistantContent::ToolCall(tool_call) => LeanPromptAssemblyItem {
            item: "call".to_string(),
            value: parse_call_key(&call_key_of(tool_call)),
        },
        AssistantContent::Reasoning(reasoning) => LeanPromptAssemblyItem {
            item: "other".to_string(),
            value: parse_suffix(&reasoning_text(reasoning), "reasoning-"),
        },
        AssistantContent::Image(_) => {
            panic!("no witness row builds an image; projection would be ambiguous")
        }
    }
}

fn user_item_of(content: &UserContent) -> LeanPromptAssemblyItem {
    match content {
        UserContent::Text(text) => LeanPromptAssemblyItem {
            item: "text".to_string(),
            value: parse_suffix(&text.text, "text-"),
        },
        other => panic!("no witness row builds {other:?}; projection would be ambiguous"),
    }
}

fn reasoning_text(reasoning: &Reasoning) -> String {
    use gents::llm::message::ReasoningContent;
    reasoning
        .content
        .iter()
        .map(|block| match block {
            ReasoningContent::Text { text, .. } => text.clone(),
            other => panic!("unexpected reasoning block in a witness row: {other:?}"),
        })
        .collect::<Vec<_>>()
        .join("")
}

/// Mirrors `history.rs::tool_call_key`: `call_id` when present, else the item id.
fn call_key_of(tool_call: &ToolCall) -> String {
    tool_call
        .call_id
        .clone()
        .unwrap_or_else(|| tool_call.id.clone())
}

/// Mirrors `history.rs::tool_result_key`.
fn result_key(tool_result: &ToolResult) -> String {
    tool_result
        .call_id
        .clone()
        .unwrap_or_else(|| tool_result.id.clone())
}

fn parse_call_key(key: &str) -> u64 {
    parse_suffix(key, "call-")
}

fn parse_suffix(value: &str, prefix: &str) -> u64 {
    value
        .strip_prefix(prefix)
        .and_then(|rest| rest.parse::<u64>().ok())
        .unwrap_or_else(|| panic!("value {value:?} is not a generated {prefix}* identity"))
}

fn rows_of(messages: &[Message]) -> Vec<LeanPromptAssemblyRow> {
    messages.iter().map(row_of_message).collect()
}

fn messages_of(rows: &[LeanPromptAssemblyRow]) -> Vec<Message> {
    rows.iter().map(message_of_row).collect()
}

/// The projection must be faithful in both directions, or every comparison
/// below would be measuring the projection rather than the sanitizer.
#[test]
fn generated_rows_round_trip_through_production_messages() {
    let cases = lean_prompt_assembly_sanitize_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly sanitize cases"
    );
    for case in cases {
        for rows in [&case.input, &case.expected, &case.expected_twice] {
            assert_eq!(
                &rows_of(&messages_of(rows)),
                rows,
                "row -> Message -> row must be the identity ({})",
                case.name
            );
        }
    }
}

/// The fence. Drives the production sanitizer with generated input and compares
/// against the generated expectation, for the whole transcript
/// (`sanitizeForProviderGlobal` on the emitted witness), for a second pass
/// (`sanitizeForProviderGlobal_idempotent`), and for every suffix
/// (`sanitizeForProviderGlobal_split_stable`). The comparisons run the whole
/// production pipeline; the only Rust-side transform is the row projection,
/// whose identity the round-trip test below pins. See the module header for
/// the global/per-turn boundary this does and does not claim.
#[test]
fn generated_sanitize_cases_drive_the_production_sanitizer() {
    let cases = lean_prompt_assembly_sanitize_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly sanitize cases"
    );

    for case in cases {
        let once = sanitize_history_for_provider(
            ProviderInputProfile::OpenAiChatCompletions,
            messages_of(&case.input),
        );
        assert_eq!(
            rows_of(&once),
            case.expected,
            "sanitize disagrees with the Lean model on case {:?}",
            case.name
        );

        let twice = sanitize_history_for_provider(
            ProviderInputProfile::OpenAiChatCompletions,
            once.clone(),
        );
        assert_eq!(
            rows_of(&twice),
            case.expected_twice,
            "sanitize is not idempotent on case {:?}",
            case.name
        );

        for split in &case.splits {
            assert!(
                split.index <= case.input.len(),
                "generated split index {} exceeds input length on case {:?}",
                split.index,
                case.name
            );
            let suffix = messages_of(&case.input[split.index..]);
            assert_eq!(
                rows_of(&sanitize_history_for_provider(
                    ProviderInputProfile::OpenAiChatCompletions,
                    suffix
                )),
                split.expected,
                "sanitize disagrees with the Lean model on case {:?} at split {}",
                case.name,
                split.index
            );
        }
    }
}

/// Fence: the Messages SSE parser reproduces `ClaudeMap.mapTurn` on every
/// generated witness (mapped ids, empty-surface / unmapped / duplicate fail closed).
#[test]
fn generated_claude_map_cases_drive_the_messages_parser() {
    let cases = lean_prompt_assembly_claude_map_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly Claude map cases"
    );
    for case in cases {
        let surface: HashSet<String> = case.surface.iter().cloned().collect();
        let sse = claude_map_blocks_as_sse(&case.blocks);
        let parsed = parse_messages_sse(&sse, &surface);
        match case.outcome.as_str() {
            "ok" => {
                let events =
                    parsed.unwrap_or_else(|err| panic!("case {} should map: {err}", case.name));
                let got_ids: Vec<u64> = events
                    .iter()
                    .filter_map(|event| match event {
                        RawStreamingChoice::ToolCall(call) => {
                            Some(call.id.parse::<u64>().unwrap_or_else(|_| {
                                panic!("case {} mapped id {} is not a Nat", case.name, call.id)
                            }))
                        }
                        _ => None,
                    })
                    .collect();
                assert_eq!(got_ids, case.ids, "mapped ids ({})", case.name);
            }
            outcome => assert_fail_closed(&case.name, outcome, parsed),
        }
    }
}

/// Shared fail-closed oracle for the ClaudeMap and stream witnesses: the
/// Lean `errorName` tag must correspond to the parser's frozen Display text.
fn assert_fail_closed(
    case_name: &str,
    outcome: &str,
    parsed: Result<Vec<RawStreamingChoice<ClaudeStreamResponse>>, CompletionError>,
) {
    let err = parsed
        .expect_err("witness outcome is an error; parser must fail closed")
        .to_string();
    let ok = match outcome {
        "emptySurface" => err.contains("fail-closed: tool_use observed"),
        o if o.starts_with("unmappedName:") => {
            let name = o.strip_prefix("unmappedName:").expect("prefix");
            err.contains("fail-closed: tool_use observed") && err.contains(name)
        }
        o if o.starts_with("duplicateId:") => err.contains(&format!(
            "fail-closed: duplicate tool_use id {}",
            o.strip_prefix("duplicateId:").expect("prefix")
        )),
        o if o.starts_with("overlappingBlock:") => err.contains(&format!(
            "fail-closed: overlapping tool_use block {}",
            o.strip_prefix("overlappingBlock:").expect("prefix")
        )),
        other => panic!("case {case_name} unknown outcome {other}"),
    };
    assert!(
        ok,
        "case {case_name}: outcome {outcome} but error was: {err}"
    );
}

fn sse_event(payload: serde_json::Value) -> String {
    let kind = payload["type"].as_str().expect("type").to_string();
    format!("event: {kind}\ndata: {payload}\n\n")
}

/// Render ClaudeMap block tags (`text`, `toolUse:id:name`, `toolResult:id`) as
/// an assistant-turn SSE body. `toolResult` never appears in an assistant turn
/// and is skipped.
fn claude_map_blocks_as_sse(blocks: &[String]) -> String {
    let mut sse = String::new();
    for (index, block) in blocks.iter().enumerate() {
        if block == "text" {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_start", "index": index,
                "content_block": {"type": "text", "text": ""}
            })));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_delta", "index": index,
                "delta": {"type": "text_delta", "text": "hi"}
            })));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_stop", "index": index
            })));
        } else if let Some(rest) = block.strip_prefix("toolUse:") {
            let (id, name) = rest
                .split_once(':')
                .unwrap_or_else(|| panic!("toolUse tag must be toolUse:id:name, got {block}"));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_start", "index": index,
                "content_block": {"type": "tool_use", "id": id, "name": name, "input": {}}
            })));
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_stop", "index": index
            })));
        } else if block.starts_with("toolResult:") {
            continue;
        } else {
            panic!("unknown Claude map block tag {block}");
        }
    }
    sse.push_str(&sse_event(serde_json::json!({"type": "message_stop"})));
    sse
}

/// Fence: the Messages SSE parser reproduces `ClaudeMap.runStream` — deltas
/// win over the start input, overlap / duplicate / unmapped fail closed, an
/// unterminated block flushes at end of stream.
#[test]
fn generated_claude_stream_cases_drive_the_messages_parser() {
    let cases = lean_prompt_assembly_claude_stream_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly Claude stream cases"
    );
    for case in cases {
        let surface: HashSet<String> = case.surface.iter().cloned().collect();
        let sse = claude_stream_events_as_sse(&case.events);
        let parsed = parse_messages_sse(&sse, &surface);
        match case.outcome.as_str() {
            "ok" => {
                let events =
                    parsed.unwrap_or_else(|err| panic!("case {} should parse: {err}", case.name));
                let got: Vec<String> = events
                    .iter()
                    .filter_map(|event| match event {
                        RawStreamingChoice::ToolCall(call) => {
                            Some(format!("{}={}", call.id, call.arguments))
                        }
                        _ => None,
                    })
                    .collect();
                let want: Vec<String> = case
                    .calls
                    .iter()
                    .map(|entry| {
                        let (id, args) = entry.split_once('=').expect("id=args");
                        let value: serde_json::Value =
                            serde_json::from_str(args).unwrap_or_else(|err| {
                                panic!("case {} witness args {args}: {err}", case.name)
                            });
                        format!("{id}={value}")
                    })
                    .collect();
                assert_eq!(got, want, "calls ({})", case.name);
            }
            outcome => assert_fail_closed(&case.name, outcome, parsed),
        }
    }
}

/// Render `StreamEvent` tags as SSE. `start:<id>:<name>:<input>` with empty
/// input emits no `input` key (Lean `none`); a non-empty input is embedded as
/// the parsed JSON object.
fn claude_stream_events_as_sse(events: &[String]) -> String {
    let mut sse = String::new();
    for tag in events {
        if let Some(text) = tag.strip_prefix("text:") {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_delta", "index": 0,
                "delta": {"type": "text_delta", "text": text}
            })));
        } else if let Some(rest) = tag.strip_prefix("start:") {
            let mut parts = rest.splitn(3, ':');
            let id = parts.next().expect("id");
            let name = parts.next().expect("name");
            let input = parts.next().unwrap_or("");
            let mut block = serde_json::json!({"type": "tool_use", "id": id, "name": name});
            if !input.is_empty() {
                block["input"] = serde_json::from_str(input)
                    .unwrap_or_else(|err| panic!("witness start input {input}: {err}"));
            }
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_start", "index": 0, "content_block": block
            })));
        } else if let Some(partial) = tag.strip_prefix("delta:") {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_delta", "index": 0,
                "delta": {"type": "input_json_delta", "partial_json": partial}
            })));
        } else if tag == "stop" {
            sse.push_str(&sse_event(serde_json::json!({
                "type": "content_block_stop", "index": 0
            })));
        } else {
            panic!("unknown Claude stream event tag {tag}");
        }
    }
    sse
}

fn claude_thinking_sse_events(events: &[LeanClaudeStreamEvent]) -> Vec<String> {
    let mut sse_events = Vec::with_capacity(events.len());
    let mut tool_index = 0;
    for event in events {
        let index = event.index.unwrap_or(tool_index);
        let payload = match event.kind.as_str() {
            "text" => serde_json::json!({
                "type": "content_block_delta", "index": index,
                "delta": {"type": "text_delta", "text": event.value.as_deref().expect("text")}
            }),
            "toolStart" => {
                tool_index = event.id.expect("tool id");
                let mut block = serde_json::json!({
                    "type": "tool_use", "id": tool_index.to_string(),
                    "name": event.name.as_deref().expect("tool name")
                });
                if let Some(input) = &event.input {
                    block["input"] = serde_json::from_str(input).expect("modeled tool input JSON");
                }
                serde_json::json!({"type":"content_block_start", "index":tool_index,
                    "content_block":block})
            }
            "toolDelta" => serde_json::json!({
                "type":"content_block_delta", "index":tool_index,
                "delta":{"type":"input_json_delta",
                    "partial_json":event.fragment.as_deref().expect("tool fragment")}
            }),
            "toolStop" => serde_json::json!({"type":"content_block_stop", "index":tool_index}),
            "thinkingStart" => serde_json::json!({
                "type":"content_block_start", "index":index,
                "content_block":{"type":"thinking",
                    "thinking":event.value.as_deref().expect("initial thinking text")}
            }),
            "thinkingDelta" => serde_json::json!({
                "type":"content_block_delta", "index":index,
                "delta":{"type":"thinking_delta",
                    "thinking":event.fragment.as_deref().expect("thinking fragment")}
            }),
            "signatureDelta" => serde_json::json!({
                "type":"content_block_delta", "index":index,
                "delta":{"type":"signature_delta",
                    "signature":event.fragment.as_deref().expect("signature fragment")}
            }),
            "redactedStart" => serde_json::json!({
                "type":"content_block_start", "index":index,
                "content_block":{"type":"redacted_thinking",
                    "data":event.data.as_deref().expect("redacted data")}
            }),
            "contentStop" => serde_json::json!({"type":"content_block_stop", "index":index}),
            other => panic!("unknown modeled Claude event {other}"),
        };
        sse_events.push(sse_event(payload));
    }
    sse_events
}

fn claude_thinking_events_as_sse(events: &[LeanClaudeStreamEvent]) -> String {
    claude_thinking_sse_events(events).concat()
}

#[test]
fn generated_claude_thinking_stream_cases_drive_native_sse_parser() {
    let cases = lean_prompt_assembly_claude_thinking_stream_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no Claude thinking stream cases"
    );
    for case in cases {
        let surface = case.surface.iter().cloned().collect::<HashSet<_>>();
        let parsed =
            parse_messages_sse_typed(&claude_thinking_events_as_sse(&case.events), &surface);
        if case.outcome != "ok" {
            use gents::claude_messages::{MessagesParseError, ThinkingParseCause};
            let error = parsed.expect_err("modeled malformed block must fail closed");
            let MessagesParseError::MalformedThinking { cause } = error else {
                panic!("{}: expected malformed thinking: {error}", case.name);
            };
            let expected = match case.outcome.as_str() {
                "missingSignature" => ThinkingParseCause::MissingSignature,
                "incompleteBlock" => ThinkingParseCause::IncompleteBlock,
                "signatureOrder" => ThinkingParseCause::SignatureOrder,
                "wrongBlock" => ThinkingParseCause::WrongBlock,
                outcome if outcome.starts_with("wrongIndex:") => ThinkingParseCause::WrongIndex(
                    outcome["wrongIndex:".len()..]
                        .parse()
                        .expect("modeled wrong index"),
                ),
                other => panic!("unknown modeled Claude thinking error {other}"),
            };
            assert_eq!(cause, expected, "{}", case.name);
            continue;
        }
        let parsed = parsed.unwrap_or_else(|error| panic!("{}: {error}", case.name));
        assert_eq!(case.steps.len(), case.events.len(), "{}", case.name);
        let mut state = gents::claude_messages::MessagesSseState::new(surface.clone());
        let mut live_preview = String::new();
        for (event, (sse, step)) in case.events.iter().zip(
            claude_thinking_sse_events(&case.events)
                .into_iter()
                .zip(case.steps.iter()),
        ) {
            if event.kind == "thinkingStart" {
                live_preview.clear();
            }
            for line in sse.lines() {
                for emitted in state
                    .push_line(line)
                    .unwrap_or_else(|error| panic!("{}: event {}: {error}", case.name, event.kind))
                {
                    if let RawStreamingChoice::ReasoningDelta { reasoning, .. } = emitted {
                        live_preview.push_str(&reasoning);
                    }
                }
            }
            match &step.provisional_thinking {
                Some(expected) => assert_eq!(
                    &live_preview, expected,
                    "{}: event {} preview",
                    case.name, event.kind
                ),
                None if event.kind == "contentStop" => live_preview.clear(),
                None => {}
            }
        }
        let observed: Vec<LeanClaudeStreamBlock> = parsed
            .iter()
            .filter_map(|event| match event {
                RawStreamingChoice::Message(value) => Some(LeanClaudeStreamBlock {
                    kind: "text".into(),
                    value: Some(value.clone()),
                    parts: None,
                    id: None,
                    name: None,
                    arguments: None,
                }),
                RawStreamingChoice::Reasoning { content, .. } => {
                    use rig::completion::message::ReasoningContent;
                    let part = match content {
                        ReasoningContent::Text { text, signature } => LeanClaudeReasoningPart {
                            kind: "text".into(),
                            payload: text.clone(),
                            signature: signature.clone(),
                        },
                        ReasoningContent::Redacted { data } => LeanClaudeReasoningPart {
                            kind: "redacted".into(),
                            payload: data.clone(),
                            signature: None,
                        },
                        other => panic!("unsupported native Claude reasoning output: {other:?}"),
                    };
                    Some(LeanClaudeStreamBlock {
                        kind: "reasoning".into(),
                        value: None,
                        parts: Some(vec![part]),
                        id: None,
                        name: None,
                        arguments: None,
                    })
                }
                RawStreamingChoice::ToolCall(call) => Some(LeanClaudeStreamBlock {
                    kind: "toolUse".into(),
                    value: None,
                    parts: None,
                    id: Some(call.id.parse().expect("modeled Nat tool id")),
                    name: Some(call.name.clone()),
                    arguments: Some(call.arguments.to_string()),
                }),
                _ => None,
            })
            .collect();
        assert_eq!(observed, case.content, "sealed content ({})", case.name);
    }
}

#[test]
fn generated_claude_initial_thinking_text_seals_in_native_accumulator() {
    use gents::llm::message::ReasoningContent;
    use gents_loop::provider_input::ProviderInputProfile;
    use gents_loop::stream_processor::AssistantTurnAccumulator;

    let cases: Vec<_> = lean_prompt_assembly_claude_thinking_stream_cases()
        .iter()
        .filter(|case| {
            case.outcome == "ok"
                && !case.content.is_empty()
                && case.content.iter().all(|block| block.kind == "reasoning")
                && case.events.iter().any(|event| {
                    event.kind == "thinkingStart"
                        && event.value.as_deref().is_some_and(|text| !text.is_empty())
                })
        })
        .collect();
    assert!(
        !cases.is_empty(),
        "Lean emitted no initial-text thinking case"
    );
    for case in cases {
        let parsed = parse_messages_sse(
            &claude_thinking_events_as_sse(&case.events),
            &HashSet::new(),
        )
        .unwrap_or_else(|error| panic!("{}: {error}", case.name));
        let mut accumulator = AssistantTurnAccumulator::default();
        for event in parsed {
            match event {
                RawStreamingChoice::ReasoningDelta { id, reasoning } => accumulator
                    .push_provider_reasoning_delta(
                        ProviderInputProfile::ClaudeMessages,
                        id,
                        &reasoning,
                    ),
                RawStreamingChoice::Reasoning { id, content } => {
                    let part = match content {
                        rig::completion::message::ReasoningContent::Text { text, signature } => {
                            ReasoningContent::Text { text, signature }
                        }
                        rig::completion::message::ReasoningContent::Redacted { data } => {
                            ReasoningContent::Redacted { data }
                        }
                        other => panic!("unexpected Claude reasoning: {other:?}"),
                    };
                    accumulator
                        .push_provider_reasoning(
                            ProviderInputProfile::ClaudeMessages,
                            Reasoning {
                                id,
                                content: vec![part],
                            },
                        )
                        .unwrap_or_else(|error| panic!("{}: {error}", case.name));
                }
                RawStreamingChoice::FinalResponse(_) => {}
                other => panic!("initial-text case emitted unrelated event: {other:?}"),
            }
        }
        let expected: Vec<_> = case
            .content
            .iter()
            .map(|block| {
                let parts = block.parts.as_ref().expect("modeled reasoning parts");
                AssistantContent::Reasoning(Reasoning {
                    id: None,
                    content: parts
                        .iter()
                        .map(|part| match part.kind.as_str() {
                            "text" => ReasoningContent::Text {
                                text: part.payload.clone(),
                                signature: part.signature.clone(),
                            },
                            "redacted" => ReasoningContent::Redacted {
                                data: part.payload.clone(),
                            },
                            other => panic!("unexpected modeled reasoning part: {other}"),
                        })
                        .collect(),
                })
            })
            .collect();
        let Some(Message::Assistant { content, .. }) = accumulator.take_message() else {
            panic!("{}: no canonical assistant message", case.name);
        };
        assert_eq!(content, expected, "{}: canonical seal", case.name);
    }
}

#[test]
fn generated_claude_narrowing_cases_bind_native_evidence_and_replay() {
    use crate::lean_vocab_test::{
        lean_prompt_assembly_claude_narrowing_cases, LeanClaudeReplayOrigin, LeanClaudeReplayUsage,
    };
    use gents_loop::claude_messages_body::{
        narrow_assistant_content, ReplayEvidenceError, ReplayOrigin, ReplayUsage,
    };

    fn outcome(error: anyhow::Error) -> &'static str {
        if let Some(error) = error.downcast_ref::<ReplayEvidenceError>() {
            return match error {
                ReplayEvidenceError::MissingOrigin => "missingContinuationOrigin",
                ReplayEvidenceError::ForeignOrigin => "foreignContinuationOrigin",
                ReplayEvidenceError::AmbiguousOrigin => "ambiguousContinuationOrigin",
                ReplayEvidenceError::MissingWitness => "missingReasoningWitness",
                ReplayEvidenceError::AlteredReasoning => "alteredReasoning",
            };
        }
        match error.to_string().as_str() {
            "Claude thinking replay requires a nonempty signature" => "missingSignature",
            "Claude redacted thinking replay has no data" => "malformedRedacted",
            "unsupported native reasoning kind in Claude replay" => "unsupportedReasoning",
            "unsupported assistant image in Claude replay" => "unsupportedReplayBlock",
            other => panic!("unexpected native replay failure: {other}"),
        }
    }

    let cases = lean_prompt_assembly_claude_narrowing_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no provenance narrowing cases"
    );
    for case in cases {
        assert_eq!(case.carriers.len(), case.rows.len(), "{}", case.name);
        let result: anyhow::Result<Vec<Vec<serde_json::Value>>> = case
            .rows
            .iter()
            .map(|row| {
                let content = native_claude_replay_content(&row.blocks);
                let expected = row.expected_reasoning.as_ref().map(|witness| {
                    witness
                        .iter()
                        .map(|block| {
                            (
                                block.block_index,
                                native_claude_reasoning_parts(&block.parts),
                            )
                        })
                        .collect()
                });
                let origin = match row.origin {
                    LeanClaudeReplayOrigin::ClaudeSubscription => ReplayOrigin::ClaudeSubscription,
                    LeanClaudeReplayOrigin::Foreign => ReplayOrigin::Foreign,
                    LeanClaudeReplayOrigin::Missing => ReplayOrigin::Missing,
                    LeanClaudeReplayOrigin::Ambiguous => ReplayOrigin::Ambiguous,
                };
                let usage = match row.usage {
                    LeanClaudeReplayUsage::Historical => ReplayUsage::Historical,
                    LeanClaudeReplayUsage::RequiredCurrent => ReplayUsage::RequiredCurrent {
                        origin,
                        expected: expected.as_ref(),
                    },
                };
                let content = narrow_assistant_content(&content, usage)?;
                let body = build_messages_body_native(
                    "claude-sonnet-5",
                    None,
                    Some(128),
                    &[Message::Assistant { id: None, content }],
                    &[],
                )?;
                let messages = body["messages"].as_array().expect("messages array");
                let mut blocks = match messages.as_slice() {
                    [] => Vec::new(),
                    [message] => message["content"]
                        .as_array()
                        .expect("assistant content")
                        .clone(),
                    _ => panic!("one modeled row produced multiple messages"),
                };
                for block in &mut blocks {
                    block
                        .as_object_mut()
                        .expect("content object")
                        .remove("cache_control");
                }
                Ok(blocks)
            })
            .collect();
        match result {
            Ok(actual) => {
                assert_eq!(case.outcome, "ok", "{}", case.name);
                let expected: Vec<_> = case
                    .replay
                    .iter()
                    .map(|row| claude_replay_json(row))
                    .collect();
                assert_eq!(actual, expected, "{}", case.name);
            }
            Err(error) => assert_eq!(outcome(error), case.outcome, "{}", case.name),
        }
    }
}

fn profile_of_order(mode: crate::lean_vocab_test::LeanAssistantOrderMode) -> ProviderInputProfile {
    match mode {
        crate::lean_vocab_test::LeanAssistantOrderMode::Grouped => {
            ProviderInputProfile::OpenAiChatCompletions
        }
        crate::lean_vocab_test::LeanAssistantOrderMode::NativePreserved => {
            ProviderInputProfile::ClaudeMessages
        }
    }
}

#[test]
fn generated_assistant_order_cases_bind_selected_provider_order() {
    use gents::compaction::history::normalize_assistant_content_order;
    let cases = crate::lean_vocab_test::lean_prompt_assembly_assistant_order_cases();
    assert!(!cases.is_empty());
    for case in cases {
        let profile = profile_of_order(case.order_mode);
        let input = vec![Message::Assistant {
            id: None,
            content: case.input.iter().map(assistant_item).collect(),
        }];
        let once = normalize_assistant_content_order(profile, input);
        assert_eq!(once.len(), 1, "{}", case.name);
        assert_eq!(
            row_of_message(&once[0]).content,
            case.expected,
            "{}",
            case.name
        );
        let twice = normalize_assistant_content_order(profile, once);
        assert_eq!(twice.len(), 1, "{}", case.name);
        assert_eq!(
            row_of_message(&twice[0]).content,
            case.expected_twice,
            "{}",
            case.name
        );
    }
}

#[test]
fn generated_mode_sanitize_cases_bind_composed_provider_view() {
    let cases = crate::lean_vocab_test::lean_prompt_assembly_mode_sanitize_cases();
    assert!(!cases.is_empty());
    for case in cases {
        let profile = profile_of_order(case.order_mode);
        let once = sanitize_history_for_provider(profile, messages_of(&case.input));
        assert_eq!(rows_of(&once), case.expected, "{}", case.name);
        let twice = sanitize_history_for_provider(profile, once);
        assert_eq!(rows_of(&twice), case.expected_twice, "{}", case.name);
    }
}

fn native_claude_reasoning_parts(
    parts: &[crate::lean_vocab_test::LeanClaudeReplayInputPart],
) -> Vec<gents::llm::message::ReasoningContent> {
    use gents::llm::message::ReasoningContent;
    parts
        .iter()
        .map(|part| {
            let payload = String::from_utf8(part.payload.clone()).expect("reconstructed UTF-8");
            match part.kind.as_str() {
                "text" => ReasoningContent::Text {
                    text: payload,
                    signature: part.signature.clone(),
                },
                "redacted" => ReasoningContent::Redacted { data: payload },
                "encrypted" => ReasoningContent::Encrypted(payload),
                "summary" => ReasoningContent::Summary(payload),
                other => panic!("unknown modeled reasoning part {other}"),
            }
        })
        .collect()
}

fn native_replay_tag(
    tag: &crate::lean_vocab_test::LeanCanonicalCoordinate,
) -> gents_loop::claude_messages_body::ReplayTag {
    use crate::lean_vocab_test::LeanCanonicalSource;
    use gents_protocol::output::OutputSource;
    let source = match &tag.source {
        LeanCanonicalSource::Provider {
            scope,
            turn,
            attempt,
        } => OutputSource::ProviderTurn {
            // Inject symbolic scope zero into the native positive sequence
            // space; no fixture relies on a particular physical spelling.
            scope: format!("inference.{}", scope.checked_add(1).expect("scope fits"))
                .parse()
                .expect("modeled provider scope"),
            turn_index: (*turn).try_into().expect("modeled turn fits"),
            attempt: (*attempt).try_into().expect("modeled attempt fits"),
        },
        LeanCanonicalSource::Tool { call } => OutputSource::ToolCall {
            tool_call_doc_id: format!("tool-{call}"),
        },
        LeanCanonicalSource::Authored { key } => OutputSource::Authored {
            key: format!("authored-{key}"),
        },
    };
    gents_loop::claude_messages_body::ReplayTag {
        request_doc_id: format!("request-{}", tag.request),
        source,
    }
}

fn native_replay_origin(
    origin: crate::lean_vocab_test::LeanClaudeReplayOrigin,
) -> gents_loop::claude_messages_body::ReplayOrigin {
    use crate::lean_vocab_test::LeanClaudeReplayOrigin as Lean;
    use gents_loop::claude_messages_body::ReplayOrigin as Native;
    match origin {
        Lean::ClaudeSubscription => Native::ClaudeSubscription,
        Lean::Foreign => Native::Foreign,
        Lean::Missing => Native::Missing,
        Lean::Ambiguous => Native::Ambiguous,
    }
}

fn replay_evidence_outcome(
    error: &gents_loop::claude_messages_body::ReplayEvidenceError,
) -> &'static str {
    use gents_loop::claude_messages_body::ReplayEvidenceError as Error;
    match error {
        Error::MissingOrigin => "missingContinuationOrigin",
        Error::ForeignOrigin => "foreignContinuationOrigin",
        Error::AmbiguousOrigin => "ambiguousContinuationOrigin",
        Error::MissingWitness => "missingReasoningWitness",
        Error::AlteredReasoning => "alteredReasoning",
    }
}

fn replay_codec_outcome(
    error: &gents_loop::claude_messages_body::AssistantCodecError,
) -> &'static str {
    use gents_loop::claude_messages_body::AssistantCodecError as Error;
    match error {
        Error::UnsupportedImage => "unsupportedReplayBlock",
        Error::MissingSignature => "missingSignature",
        Error::EmptyRedacted => "malformedRedacted",
        Error::UnsupportedReasoning => "unsupportedReasoning",
    }
}

fn replay_checkpoint_outcome(
    error: &gents_loop::claude_messages_body::ReplayCheckpointError,
) -> &'static str {
    use gents_loop::claude_messages_body::ReplayCheckpointError as Error;
    match error {
        Error::InvalidSplit => "invalidReplaySplit",
        Error::InvalidAssociation => "invalidReplayAssociation",
        Error::DuplicateAssociation => "duplicateReplayAssociation",
        Error::RequiredInPrefix => "requiredReplayInPrefix",
        Error::MissingRequired => "missingRequiredReplay",
        Error::Evidence(error) => replay_evidence_outcome(error),
        Error::Codec(error) => replay_codec_outcome(error),
    }
}

#[test]
fn generated_protected_replay_compaction_cases_bind_native_split_and_checkpoint() {
    use crate::lean_vocab_test::lean_protected_replay_compaction_cases;
    use gents_loop::claude_messages_body::{prepare_replay_checkpoint, TaggedAssistantRow};
    use gents_loop::compaction::history::protected_pair_safe_split_index;

    let cases = lean_protected_replay_compaction_cases();
    assert_eq!(cases.len(), 5);
    for case in cases {
        let messages =
            super::streaming_compaction::compaction_messages_for_count(case.message_count);
        let assistant_count = messages
            .iter()
            .filter(|message| matches!(message, Message::Assistant { .. }))
            .count();
        assert_eq!(case.rows.len(), assistant_count, "{}", case.name);

        let split = protected_pair_safe_split_index(&messages, case.raw_index, case.max_prefix);
        assert_eq!(
            split, case.selected_split,
            "{}: pair-safe protected split",
            case.name
        );
        let outcome = match split {
            None => "cannot_fit",
            Some(split) => {
                let assistant_split = messages[..split]
                    .iter()
                    .filter(|message| matches!(message, Message::Assistant { .. }))
                    .count();
                let rows = case
                    .rows
                    .iter()
                    .map(|row| TaggedAssistantRow {
                        source: row.source.as_ref().map(native_replay_tag),
                        id: None,
                        content: native_claude_replay_content(&row.blocks),
                    })
                    .collect();
                match prepare_replay_checkpoint(
                    case.required.iter().map(native_replay_tag).collect(),
                    rows,
                    assistant_split,
                ) {
                    Ok(_) => "ok",
                    Err(error) => replay_checkpoint_outcome(&error),
                }
            }
        };
        assert_eq!(outcome, case.outcome, "{}: composed checkpoint", case.name);
    }
}

#[test]
fn generated_claude_checkpoint_cases_bind_selected_assistant_projection() {
    use crate::lean_vocab_test::lean_prompt_assembly_claude_checkpoint_cases;
    use gents_loop::claude_messages_body::{
        prepare_replay_checkpoint, restore_and_narrow_replay, ResolvedReplayEvidence,
        TaggedAssistantRow,
    };
    let cases = lean_prompt_assembly_claude_checkpoint_cases();
    assert!(!cases.is_empty());
    for case in cases {
        assert_eq!(case.carrier_ids.len(), case.rows.len(), "{}", case.name);
        let rows = case
            .rows
            .iter()
            .zip(&case.carrier_ids)
            .map(|(row, id)| TaggedAssistantRow {
                source: row.source.as_ref().map(native_replay_tag),
                id: Some(id.clone()),
                content: native_claude_replay_content(&row.blocks),
            })
            .collect();
        let checkpoint = match prepare_replay_checkpoint(
            case.required.iter().map(native_replay_tag).collect(),
            rows,
            case.split,
        ) {
            Err(error) => {
                assert_eq!(
                    replay_checkpoint_outcome(&error),
                    case.outcome,
                    "{}",
                    case.name
                );
                assert!(
                    case.prefix_rows.is_empty()
                        && case.retained.is_empty()
                        && case.replay.is_empty()
                );
                continue;
            }
            Ok(checkpoint) => checkpoint,
        };
        for (actual, expected, offset) in [
            (&checkpoint.prefix_rows, &case.prefix_rows, 0),
            (&checkpoint.retained, &case.retained, case.prefix_rows.len()),
        ] {
            assert_eq!(actual.len(), expected.len(), "{}", case.name);
            for (index, (actual, expected)) in actual.iter().zip(expected).enumerate() {
                assert_eq!(
                    actual.source,
                    expected.source.as_ref().map(native_replay_tag),
                    "{}",
                    case.name
                );
                assert_eq!(
                    actual.content,
                    native_claude_replay_content(&expected.blocks),
                    "{}",
                    case.name
                );
                assert_eq!(
                    actual.id.as_ref(),
                    Some(&case.carrier_ids[offset + index]),
                    "{}",
                    case.name
                );
            }
        }
        let resolutions = case
            .resolutions
            .iter()
            .map(|entry| {
                (
                    native_replay_tag(&entry.tag),
                    ResolvedReplayEvidence {
                        origin: native_replay_origin(entry.origin),
                        reasoning: entry
                            .expected_reasoning
                            .iter()
                            .map(|block| {
                                (
                                    block.block_index,
                                    native_claude_reasoning_parts(&block.parts),
                                )
                            })
                            .collect(),
                    },
                )
            })
            .collect::<Vec<_>>();
        // Only representation translation: duplicate resolution records stay
        // duplicated, and witnesses come from modeled resolver inputs rather
        // than from the content being checked.
        match restore_and_narrow_replay(&checkpoint, |tag| {
            resolutions
                .iter()
                .filter(|(candidate, _)| candidate == tag)
                .map(|(_, evidence)| evidence.clone())
                .collect()
        }) {
            Err(error) => assert_eq!(
                replay_checkpoint_outcome(&error),
                case.outcome,
                "{}",
                case.name
            ),
            Ok(prepared) => {
                assert_eq!(case.outcome, "ok", "{}", case.name);
                assert_eq!(prepared.len(), case.replay.len(), "{}", case.name);
                for ((row, selected), expected) in
                    prepared.iter().zip(&checkpoint.retained).zip(&case.replay)
                {
                    assert_eq!(row.source, selected.source, "{}", case.name);
                    assert_eq!(row.id, selected.id, "{}", case.name);
                    assert_eq!(
                        row.wire_blocks,
                        claude_replay_json(expected),
                        "{}",
                        case.name
                    );
                }
                // The live body owner receives the same narrowed native rows.
                // This assistant-only test does not claim full request restore
                // or provider budgeting is wired to the result yet.
                let native = prepared
                    .iter()
                    .map(|row| Message::Assistant {
                        id: row.id.clone(),
                        content: row.content.clone(),
                    })
                    .collect::<Vec<_>>();
                let body =
                    build_messages_body_native("claude-sonnet-5", None, Some(128), &native, &[])
                        .unwrap_or_else(|error| panic!("{}: {error}", case.name));
                let actual = body["messages"]
                    .as_array()
                    .expect("messages")
                    .iter()
                    .map(|message| {
                        let mut blocks = message["content"]
                            .as_array()
                            .expect("assistant content")
                            .clone();
                        for block in &mut blocks {
                            block
                                .as_object_mut()
                                .expect("content object")
                                .remove("cache_control");
                        }
                        blocks
                    })
                    .collect::<Vec<_>>();
                let expected = prepared
                    .iter()
                    .filter(|row| !row.wire_blocks.is_empty())
                    .map(|row| row.wire_blocks.clone())
                    .collect::<Vec<_>>();
                assert_eq!(actual, expected, "{}", case.name);
            }
        }
    }
}

fn native_claude_replay_content(
    blocks: &[crate::lean_vocab_test::LeanClaudeReplayInputBlock],
) -> Vec<AssistantContent> {
    let mut content = Vec::new();
    for block in blocks {
        match block.kind.as_str() {
            "text" => content.push(AssistantContent::Text(Text {
                text: String::from_utf8(block.payload.clone().expect("text payload"))
                    .expect("reconstructed UTF-8"),
            })),
            "reasoning" => {
                let parts =
                    native_claude_reasoning_parts(block.parts.as_ref().expect("reasoning parts"));
                content.push(AssistantContent::Reasoning(Reasoning {
                    id: block.id.clone(),
                    content: parts,
                }));
            }
            "toolCall" => {
                let arguments = String::from_utf8(block.arguments.clone().expect("arguments"))
                    .expect("reconstructed UTF-8");
                content.push(AssistantContent::ToolCall(ToolCall {
                    id: block.id.clone().expect("provider tool id"),
                    call_id: block.call_id.clone(),
                    function: ToolFunction {
                        name: block.name.clone().expect("tool name"),
                        arguments: serde_json::from_str(&arguments)
                            .expect("modeled JSON arguments"),
                    },
                    signature: block.signature.clone(),
                    additional_params: block.additional_params.as_ref().map(|value| {
                        serde_json::from_str(value).expect("modeled additional params JSON")
                    }),
                }));
            }
            "unsupportedMedia" => content.push(AssistantContent::Image(Image::default())),
            other => panic!("unsupported modeled replay input block {other}"),
        }
    }
    content
}

#[test]
fn generated_claude_replay_cases_drive_native_messages_body() {
    let cases = lean_prompt_assembly_claude_replay_cases();
    assert!(!cases.is_empty(), "Lean emitted no Claude replay cases");
    for case in cases {
        let content = native_claude_replay_content(&case.blocks);
        let history = [Message::Assistant { id: None, content }];
        let result = build_messages_body_native("claude-sonnet-5", None, Some(128), &history, &[]);
        if case.outcome != "ok" {
            let error = result.expect_err("modeled unsupported replay must fail closed");
            let codec = error
                .downcast_ref::<gents_loop::claude_messages_body::AssistantCodecError>()
                .unwrap_or_else(|| {
                    panic!(
                        "{}: expected native assistant codec error: {error:#}",
                        case.name
                    )
                });
            assert_eq!(replay_codec_outcome(codec), case.outcome, "{}", case.name);
            continue;
        }
        let body = result.unwrap_or_else(|error| panic!("{}: {error}", case.name));
        let mut actual = if case.replay.is_empty() {
            assert!(
                body["messages"].as_array().is_none_or(Vec::is_empty),
                "{}: empty replay must omit assistant message: {body}",
                case.name
            );
            Vec::new()
        } else {
            body["messages"][0]["content"]
                .as_array()
                .unwrap_or_else(|| panic!("{}: missing assistant content: {body}", case.name))
                .clone()
        };
        for block in &mut actual {
            block
                .as_object_mut()
                .expect("content object")
                .remove("cache_control");
        }
        let expected = claude_replay_json(&case.replay);
        assert_eq!(actual, expected, "replay ({})", case.name);
    }
}

fn claude_replay_json(
    blocks: &[crate::lean_vocab_test::LeanClaudeReplayBlock],
) -> Vec<serde_json::Value> {
    blocks
        .iter()
        .map(|block| {
            let payload = || {
                String::from_utf8(block.payload.clone().expect("replay payload"))
                    .expect("reconstructed UTF-8")
            };
            match block.kind.as_str() {
                "text" => serde_json::json!({"type":"text", "text":payload()}),
                "signedThinking" => serde_json::json!({
                    "type":"thinking", "thinking":payload(),
                    "signature":block.signature.as_deref().expect("modeled signature")
                }),
                "redactedThinking" => serde_json::json!({
                    "type":"redacted_thinking", "data":payload()
                }),
                "toolUse" => {
                    let arguments = String::from_utf8(block.arguments.clone().expect("arguments"))
                        .expect("reconstructed UTF-8");
                    serde_json::json!({
                        "type":"tool_use", "id":block.id.as_deref().expect("provider id"),
                        "name":block.name.as_deref().expect("tool name"),
                        "input":serde_json::from_str::<serde_json::Value>(&arguments)
                            .expect("modeled JSON arguments")
                    })
                }
                other => panic!("unknown modeled replay output {other}"),
            }
        })
        .collect()
}

/// Fence: `build_messages_body_native` reproduces `ClaudeMap.systemBlocks` /
/// `splitSystem` / `toolsField` — identity first, preamble, then `System`
/// rows in order; `tools` absent for an empty surface.
#[test]
fn generated_claude_body_cases_drive_the_body_builder() {
    let cases = lean_prompt_assembly_claude_body_cases();
    assert!(
        !cases.is_empty(),
        "Lean emitted no PromptAssembly Claude body cases"
    );
    for case in cases {
        let history: Vec<Message> = case
            .rows
            .iter()
            .map(|row| {
                if let Some(text) = row.strip_prefix("system:") {
                    Message::System {
                        content: text.to_string(),
                    }
                } else if row == "other:assistant" {
                    Message::assistant("ok")
                } else {
                    Message::user("hi")
                }
            })
            .collect();
        let tools: Vec<rig::completion::ToolDefinition> = case
            .tools
            .iter()
            .map(|name| rig::completion::ToolDefinition {
                name: name.clone(),
                description: name.clone(),
                parameters: serde_json::json!({"type": "object"}),
            })
            .collect();
        let mut body = build_messages_body_native(
            "claude-sonnet-5",
            case.preamble.as_deref(),
            None,
            &history,
            &tools,
        )
        .expect("Claude body");
        gents::claude_messages::apply_reasoning_parameters(
            "claude-sonnet-5",
            &serde_json::json!({
                (gents::claude_messages::ADVERTISED_REASONING_EFFORTS_PARAM):
                    case.supported_efforts,
                "output_config": {"effort": case.effort}
            }),
            &mut body,
        );
        assert_eq!(
            body["output_config"]["effort"].as_str(),
            case.selected_effort.as_deref(),
            "{}",
            case.name
        );
        assert_eq!(
            body.get("thinking").is_some(),
            case.selected_effort.is_some(),
            "{}",
            case.name
        );
        let system: Vec<String> = body["system"]
            .as_array()
            .unwrap_or_else(|| panic!("case {} system array: {body}", case.name))
            .iter()
            .map(|block| block["text"].as_str().expect("text").to_string())
            .collect();
        assert_eq!(system, case.system, "system blocks ({})", case.name);
        assert_eq!(system[0], CLAUDE_CODE_IDENTITY, "case {}", case.name);
        assert_eq!(
            body.get("tools").is_some(),
            case.tools_present,
            "tools key ({})",
            case.name
        );
        let leaked = body["messages"]
            .as_array()
            .expect("messages")
            .iter()
            .any(|message| {
                message["content"].as_array().is_some_and(|blocks| {
                    blocks.iter().any(|block| {
                        block["text"]
                            .as_str()
                            .is_some_and(|t| t.starts_with("system: "))
                    })
                })
            });
        assert!(
            !leaked,
            "System row leaked into messages ({}): {body}",
            case.name
        );
    }
}

/// Pairing identity: calls and results pair on `call_id.unwrap_or(id)`
/// (`history.rs::tool_call_key` / `tool_result_key`), never on the item id
/// alone. The Lean model abstracts both into one `ToolCallId`, so this
/// below-the-model identity is fenced only here: a pair whose `call_id` differs
/// from both item ids (the OpenAI responses-API shape) must survive sanitize.
#[test]
fn pairing_identity_uses_call_id_over_item_id() {
    let history = vec![
        Message::Assistant {
            id: None,
            content: vec![AssistantContent::ToolCall(ToolCall {
                id: "item-9".to_string(),
                call_id: Some("fc-1".to_string()),
                function: ToolFunction {
                    name: "echo".to_string(),
                    arguments: serde_json::json!({}),
                },
                signature: None,
                additional_params: None,
            })],
        },
        Message::User {
            content: vec![UserContent::ToolResult(ToolResult {
                id: "out-3".to_string(),
                call_id: Some("fc-1".to_string()),
                content: vec![ToolResultContent::Text(Text {
                    text: "fc-1-result".to_string(),
                })],
            })],
        },
    ];
    assert_eq!(
        sanitize_history_for_provider(ProviderInputProfile::OpenAiChatCompletions, history.clone()),
        history
    );
}

/// Below the model: a user message may carry plain content *and* tool results
/// in one message. The model's row projection has no such row (production
/// threads one result per message), so this shape is fenced only here.
#[test]
fn mixed_user_message_keeps_plain_content_and_drops_orphaned_result() {
    let history = vec![Message::User {
        content: vec![
            UserContent::Text(Text {
                text: "still here".to_string(),
            }),
            UserContent::ToolResult(ToolResult {
                id: "gone".to_string(),
                call_id: Some("gone".to_string()),
                content: vec![ToolResultContent::Text(Text {
                    text: "orphan".to_string(),
                })],
            }),
        ],
    }];
    assert_eq!(
        sanitize_history_for_provider(ProviderInputProfile::OpenAiChatCompletions, history),
        vec![Message::User {
            content: vec![UserContent::Text(Text {
                text: "still here".to_string(),
            })],
        }],
        "the orphaned result must go and the plain content must stay"
    );
}

// ---------------------------------------------------------------------------
// The owned-loop chokepoint.
//
// The claim `proofs/README.md` makes — and that `sanitize_history_for_provider`
// depends on — is that EVERY completion request in the system is born in the
// owned loop, which sanitizes loaded history at entry (`run_loop_stream`). The
// sanitize fence above is only worth anything if nothing bypasses it.
//
// Two source scans keep that honest. The first pins the set of files allowed to
// invoke a provider at all; a bypass would have to show up there. The second
// pins the set of files allowed to enter the owned loop, so a new completion
// path is visible in review rather than silent.
// ---------------------------------------------------------------------------

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .find(|path| path.join("crates/gents/proofs/lakefile.lean").exists())
        .expect("repository root should contain crates/gents/proofs/lakefile.lean")
        .to_path_buf()
}

/// Every non-test Rust source of the two crates the completion path lives
/// in.
///
/// `gents-loop` is walked as well as `gents`: the owned loop moved there,
/// and a scan that only looked here would report an empty seam and call it
/// clean, which is the one answer these tests must never give.
fn production_sources() -> Vec<(String, String)> {
    let root = repo_root();
    let mut out = Vec::new();
    let mut stack = vec![
        root.join("crates/gents/src"),
        root.join("crates/gents-loop/src"),
    ];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
        {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
                continue;
            }
            let relative = path
                .strip_prefix(&root)
                .expect("path under repo root")
                .to_string_lossy()
                .replace('\\', "/");
            // Test-only sources are not production call sites. Test code in
            // these crates lives in separate files rather than inline
            // `#[cfg(test)]` modules, so excluding by path is sufficient, and
            // unlike truncating at the first `#[cfg(test)]` it does not also
            // discard the file's real body (those markers sit at the top of
            // `loop_stream.rs` and `compaction.rs`, declaring `mod tests;`).
            // `gents` spells them `tests.rs`, `gents-loop` spells them
            // `<module>_tests.rs`; both are excluded, or the loop's own tests
            // would read as production call sites.
            let file_name = relative.rsplit('/').next().unwrap_or("");
            if relative.ends_with("/tests.rs")
                || relative.contains("/tests/")
                || file_name.ends_with("_tests.rs")
                || file_name.ends_with("_test.rs")
                || relative.contains("test_support")
                || relative.contains("lean_vocab_test")
            {
                continue;
            }
            let source = std::fs::read_to_string(&path)
                .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
            out.push((relative, source));
        }
    }
    out.sort();
    out
}

fn files_containing(needles: &[&str]) -> BTreeSet<String> {
    production_sources()
        .into_iter()
        .filter(|(_, source)| needles.iter().any(|needle| source.contains(needle)))
        .map(|(path, _)| path)
        .collect()
}

/// No completion request may be issued outside the owned loop and the admission
/// wrapper it passes through. A new file here means a provider call that never
/// saw `sanitize_history_for_provider` — report it before fixing it.
#[test]
fn provider_invocations_are_confined_to_the_owned_loop_seam() {
    let expected = BTreeSet::from([
        // Builds the request and sends it: the one owned-loop seam.
        "crates/gents-loop/src/loop_stream.rs".to_string(),
        // Wraps a model to apply admission control; receives an
        // already-assembled request from the owned loop.
        "crates/gents/src/admission/client.rs".to_string(),
    ]);
    let found = files_containing(&[".completion_request(", ".completion(", ".stream("]);
    assert_eq!(
        found, expected,
        "provider invocation escaped the owned-loop seam; every completion request \
         must be born in run_loop_stream, which sanitizes loaded history at entry"
    );
}

/// The owned loop's entry points. Sanitization happens once, at the top of
/// `run_loop_stream`; every production completion path must come through here.
#[test]
fn owned_loop_entry_points_are_registered() {
    let expected = BTreeSet::from([
        // Text and typed helpers wrap `run_loop_stream`.
        "crates/gents-loop/src/loop_stream/one_shot.rs".to_string(),
        // Daemon request execution: the main path.
        "crates/gents/src/agent/daemon/inference.rs".to_string(),
        // Conversation title generation.
        "crates/gents/src/agent/daemon/title.rs".to_string(),
        // Compaction summarization.
        "crates/gents-loop/src/compaction.rs".to_string(),
        // One-shot CLI runs.
        "crates/gents/src/oneshot.rs".to_string(),
    ]);
    // Both spellings of each call. The loop's entry points are generic over
    // the session hook now, so a caller that has to name the hook writes
    // `run_loop_to_text::<M, DefraSessionHook>(...)` and a needle ending in
    // `(` would miss it. Missing an entry point here is the failure that
    // matters: it reads as "no new completion path", which is exactly what
    // this test exists to disprove.
    let found = files_containing(&[
        "run_loop_stream(",
        "run_loop_stream::<",
        "run_loop_to_text(",
        "run_loop_to_text::<",
        "run_loop_to_typed(",
        "run_loop_to_typed::<",
    ]);
    assert_eq!(
        found, expected,
        "the set of owned-loop entry points changed; a new completion path must be \
         reviewed against the sanitize-at-entry chokepoint"
    );
}

// ---------------------------------------------------------------------------
// The public constructor below starts with no available skills. This checks
// reminder lookup against that empty catalog only. Context whitelist selection,
// owner/enabled filtering, and reminders for selected available skills need the
// runtime loader migration; request-selected IDs are not the context whitelist.
// ---------------------------------------------------------------------------

#[test]
fn empty_skill_catalog_contributes_no_reminders() {
    use gents::prompt::LayeredPromptBuilder;

    let builder =
        LayeredPromptBuilder::for_behavior("literal preamble", "fence", &["bash"], false, &[]);

    assert!(
        builder.selected_skill_reminders(&[]).is_empty(),
        "an empty whitelist must not produce skill reminders"
    );

    assert!(
        builder
            .selected_skill_reminders(&["not-installed".to_string()])
            .is_empty(),
        "an unresolvable selection must not produce skill reminders"
    );
    assert!(
        builder
            .selected_skill_reminders(&["  ".to_string()])
            .is_empty(),
        "a blank selection entry must not produce skill reminders"
    );
}
