//! Rust consumer of the exact immutable ToolFact foundation model (#1073).
//! The legacy model authorizes exact fact joins only; model-facing projection
//! authority belongs to `ToolFact.ExecutionSplit` and production truncation.

use crate::lean_vocab_test::{
    lean_omission_phase_matrix_cases, lean_tool_execution_split_cases, lean_tool_fact_cases,
    lean_tool_output_projection_cases, lean_tool_terminal_evidence_cases,
    LeanToolExecutionSplitCase, LeanToolFactCase, LeanToolOutputProjectionCase,
};

#[allow(clippy::too_many_arguments)]
fn witness(
    name: &str,
    operation: &str,
    disposition: &str,
    twins: usize,
    full_output: bool,
    approval: bool,
    result_durable: bool,
    approval_durable: bool,
    projection: bool,
    immutable_noop: bool,
    call_signer: u64,
    result_cid: u64,
) -> LeanToolFactCase {
    LeanToolFactCase {
        name: name.to_owned(),
        operation: operation.to_owned(),
        disposition: disposition.to_owned(),
        visible_logical_twins: twins,
        full_output,
        call_doc_id: 100,
        call_cid: 10,
        call_signer_did: call_signer,
        result_doc_id: 200,
        result_cid,
        result_signer_did: 8,
        approval_doc_id: approval.then_some(300),
        approval_cid: approval.then_some(30),
        approval_signer_did: approval.then_some(9),
        result_durable,
        approval_durable,
        result_pins_exact_call: result_durable,
        approval_pins_exact_call: approval_durable,
        exact_fact_join: projection,
        immutable_noop,
    }
}

#[test]
fn generated_omission_phase_matrix_matches_the_production_predicate_exhaustively() {
    fn persisted(value: &str) -> &str {
        match value {
            "awaiting_approval" => "awaitingApproval",
            "timed_out" => "timedOut",
            "pre_dispatch_failure" => "preDispatchFailure",
            "approval_denied" => "approvalDenied",
            "execution_lost" => "executionLost",
            "recovery_failure" => "recoveryFailure",
            "child_dead" => "childDead",
            "child_superseded" => "childSuperseded",
            other => other,
        }
    }

    let cases = lean_omission_phase_matrix_cases();
    assert_eq!(cases.len(), 8 * 7 * 7, "Lean matrix must be exhaustive");
    for case in cases {
        assert_eq!(
            gents::tool_call_lifecycle::tool_output_omission_transition_allowed(
                persisted(&case.reason),
                persisted(&case.source_phase),
                persisted(&case.terminal_phase),
            ),
            case.allowed,
            "reason={} source={} terminal={}",
            case.reason,
            case.source_phase,
            case.terminal_phase,
        );
    }
}

pub(super) fn generated_cases_pin_exact_immutable_tool_facts() {
    let expected = [
        witness(
            "call_fact_applied",
            "commit_call",
            "applied",
            0,
            true,
            false,
            false,
            false,
            false,
            false,
            7,
            20,
        ),
        witness(
            "identical_call_replay_is_idempotent",
            "commit_call",
            "observed_identical",
            1,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "logical_key_call_twins_fail_closed",
            "commit_call",
            "rejected",
            2,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "unsigned_call_is_rejected",
            "commit_call",
            "rejected",
            0,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "full_result_applied",
            "commit_result",
            "applied",
            0,
            true,
            false,
            true,
            false,
            true,
            false,
            7,
            20,
        ),
        witness(
            "identical_result_replay_is_idempotent",
            "commit_result",
            "observed_identical",
            1,
            true,
            false,
            true,
            false,
            true,
            true,
            7,
            20,
        ),
        witness(
            "mismatched_result_replay_is_rejected",
            "commit_result",
            "rejected",
            1,
            true,
            false,
            true,
            false,
            true,
            true,
            7,
            20,
        ),
        witness(
            "logical_key_result_twins_fail_closed",
            "commit_result",
            "rejected",
            2,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "incomplete_output_is_rejected",
            "commit_result",
            "rejected",
            0,
            false,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "unsigned_result_is_rejected",
            "commit_result",
            "rejected",
            0,
            true,
            false,
            false,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "approval_applied_with_exact_call",
            "commit_approval",
            "applied",
            0,
            true,
            true,
            true,
            true,
            true,
            false,
            7,
            20,
        ),
        witness(
            "identical_approval_replay_is_idempotent",
            "commit_approval",
            "observed_identical",
            1,
            true,
            true,
            true,
            true,
            true,
            true,
            7,
            20,
        ),
        witness(
            "logical_key_approval_twins_fail_closed",
            "commit_approval",
            "rejected",
            2,
            true,
            true,
            true,
            false,
            false,
            true,
            7,
            20,
        ),
        witness(
            "wrong_result_cid_projection_is_rejected",
            "project",
            "not_attempted",
            1,
            true,
            true,
            true,
            true,
            false,
            true,
            7,
            21,
        ),
        witness(
            "wrong_call_signer_projection_is_rejected",
            "project",
            "not_attempted",
            1,
            true,
            true,
            true,
            true,
            false,
            true,
            77,
            20,
        ),
    ];

    assert_eq!(lean_tool_fact_cases(), expected);
    assert!(expected
        .iter()
        .filter(|row| row.disposition == "rejected")
        .all(|row| row.immutable_noop));
}

pub(super) fn generated_cases_pin_exact_execution_split() {
    let expected = [
        LeanToolExecutionSplitCase {
            name: "completion_requires_exact_running_output".into(),
            operation: "complete_execution".into(),
            disposition: "applied".into(),
            exact_projection: true,
            output_pins_running: true,
            terminal_output_closed: true,
            owner_preserved: true,
            approval_pins_held: false,
            immutable_noop: false,
        },
        LeanToolExecutionSplitCase {
            name: "completion_replay_is_idempotent".into(),
            operation: "complete_execution".into(),
            disposition: "observed_identical".into(),
            exact_projection: true,
            output_pins_running: true,
            terminal_output_closed: true,
            owner_preserved: true,
            approval_pins_held: false,
            immutable_noop: true,
        },
        LeanToolExecutionSplitCase {
            name: "completion_rejects_non_current_head".into(),
            operation: "complete_execution".into(),
            disposition: "rejected".into(),
            exact_projection: false,
            output_pins_running: false,
            terminal_output_closed: false,
            owner_preserved: false,
            approval_pins_held: false,
            immutable_noop: true,
        },
        LeanToolExecutionSplitCase {
            name: "competing_output_proposal_is_unbound".into(),
            operation: "commit_output".into(),
            disposition: "applied".into(),
            exact_projection: false,
            output_pins_running: false,
            terminal_output_closed: false,
            owner_preserved: false,
            approval_pins_held: false,
            immutable_noop: false,
        },
        LeanToolExecutionSplitCase {
            name: "output_rejects_wrong_execution_version".into(),
            operation: "commit_output".into(),
            disposition: "rejected".into(),
            exact_projection: false,
            output_pins_running: false,
            terminal_output_closed: false,
            owner_preserved: false,
            approval_pins_held: false,
            immutable_noop: true,
        },
        LeanToolExecutionSplitCase {
            name: "approval_chain_pins_held_execution".into(),
            operation: "approve_and_complete".into(),
            disposition: "applied".into(),
            exact_projection: true,
            output_pins_running: true,
            terminal_output_closed: true,
            owner_preserved: true,
            approval_pins_held: true,
            immutable_noop: false,
        },
        LeanToolExecutionSplitCase {
            name: "approval_replay_is_idempotent".into(),
            operation: "commit_approval".into(),
            disposition: "observed_identical".into(),
            exact_projection: false,
            output_pins_running: false,
            terminal_output_closed: false,
            owner_preserved: false,
            approval_pins_held: false,
            immutable_noop: true,
        },
        LeanToolExecutionSplitCase {
            name: "approval_rejects_non_held_execution".into(),
            operation: "commit_approval".into(),
            disposition: "rejected".into(),
            exact_projection: false,
            output_pins_running: false,
            terminal_output_closed: false,
            owner_preserved: false,
            approval_pins_held: false,
            immutable_noop: true,
        },
    ];

    assert_eq!(lean_tool_execution_split_cases(), expected);
}

pub(super) fn generated_cases_bind_model_projection_to_exact_output() {
    let expected = [
        LeanToolOutputProjectionCase {
            name: "canonical_bounded_projection_is_accepted".into(),
            observation: "canonical".into(),
            observed_hash: 303,
            accepted: true,
            full_output_preserved: true,
        },
        LeanToolOutputProjectionCase {
            name: "full_output_hash_is_not_a_model_projection".into(),
            observation: "full_output".into(),
            observed_hash: 202,
            accepted: false,
            full_output_preserved: true,
        },
        LeanToolOutputProjectionCase {
            name: "forged_terminal_projection_is_rejected".into(),
            observation: "forged".into(),
            observed_hash: 999,
            accepted: false,
            full_output_preserved: true,
        },
    ];

    assert_eq!(lean_tool_output_projection_cases(), expected);
}

pub(super) fn generated_cases_close_terminal_output_or_omission_evidence() {
    let expected = [
        (
            "failed_execution_retains_full_output",
            "applied",
            "output",
            "failed",
            "",
            "absent",
            false,
            false,
        ),
        (
            "failed_output_terminal_replay_is_idempotent",
            "observed_identical",
            "output",
            "failed",
            "",
            "absent",
            false,
            true,
        ),
        (
            "timeout_has_typed_omission",
            "applied",
            "omission",
            "timed_out",
            "timed_out",
            "absent",
            false,
            false,
        ),
        (
            "held_timeout_has_typed_omission_without_verdict",
            "applied",
            "omission",
            "timed_out",
            "timed_out",
            "absent",
            false,
            false,
        ),
        (
            "approved_running_timeout_retains_call_edge",
            "applied",
            "omission",
            "timed_out",
            "timed_out",
            "approved_running_call_edge",
            true,
            false,
        ),
        (
            "cancellation_has_typed_omission",
            "applied",
            "omission",
            "cancelled",
            "cancelled",
            "absent",
            false,
            false,
        ),
        (
            "predispatch_failure_has_typed_omission",
            "applied",
            "omission",
            "failed",
            "pre_dispatch_failure",
            "absent",
            false,
            false,
        ),
        (
            "execution_loss_has_typed_omission",
            "applied",
            "omission",
            "failed",
            "execution_lost",
            "absent",
            false,
            false,
        ),
        (
            "recovery_failure_has_typed_omission",
            "applied",
            "omission",
            "failed",
            "recovery_failure",
            "absent",
            false,
            false,
        ),
        (
            "dead_child_has_typed_omission",
            "applied",
            "omission",
            "failed",
            "child_dead",
            "absent",
            false,
            false,
        ),
        (
            "superseded_child_has_typed_omission",
            "applied",
            "omission",
            "failed",
            "child_superseded",
            "absent",
            false,
            false,
        ),
        (
            "approval_denial_pins_approval_and_omission",
            "applied",
            "omission",
            "failed",
            "approval_denied",
            "denial_call_edge",
            true,
            false,
        ),
        (
            "omission_replay_is_idempotent",
            "observed_identical",
            "omission",
            "timed_out",
            "timed_out",
            "absent",
            false,
            true,
        ),
        (
            "competing_omission_proposal_is_unbound",
            "applied",
            "none",
            "",
            "",
            "",
            false,
            false,
        ),
        (
            "wrong_phase_reason_pair_is_rejected",
            "rejected",
            "none",
            "",
            "",
            "",
            false,
            true,
        ),
        (
            "omission_terminal_replay_is_idempotent",
            "observed_identical",
            "omission",
            "timed_out",
            "timed_out",
            "absent",
            false,
            true,
        ),
    ];
    let actual = lean_tool_terminal_evidence_cases();
    assert_eq!(actual.len(), expected.len());

    for (row, expected) in actual.iter().zip(expected) {
        assert_eq!(
            (
                row.name.as_str(),
                row.disposition.as_str(),
                row.evidence_kind.as_str(),
                row.terminal_phase.as_str(),
                row.omission_reason.as_str(),
                row.approval_edge_kind.as_str(),
                row.exact_approval_bound,
                row.immutable_noop,
            ),
            expected
        );
        assert!(!row.operation.is_empty());
        if row.exact_projection {
            assert!(row.evidence_closed);
            assert!(row.mutually_exclusive);
            assert!(row.owner_preserved);
            assert!(row.phase_reason_valid);
        }
    }
}
